defmodule TeacherAssistant.Accounts do
  use Ash.Domain,
    otp_app: :teacher_assistant

  alias TeacherAssistant.Accounts.{SchoolInvitation, SchoolMembership, SchoolProfile, User}
  alias TeacherAssistant.Accounts.User.Senders.SendSchoolInvitationEmail
  alias TeacherAssistant.Scope

  resources do
    resource TeacherAssistant.Accounts.Token

    resource User do
      define :create_user, action: :register_with_password
      define :promote_to_admin
    end

    resource SchoolMembership

    resource SchoolInvitation do
      define :revoke_invitation, action: :revoke
    end

    resource SchoolProfile do
      define :update_school_profile, action: :update
      define :verify_school, action: :verify, args: [:verified_by_user_id]
      define :reject_school, action: :reject, args: [:verified_by_user_id, :rejection_reason]
    end
  end

  authorization do
    authorize :by_default
  end

  @doc "Whether the scope may invite and manage staff (head)."
  def can_manage_staff?(scope), do: Ash.can?({SchoolInvitation, :create}, scope)

  @doc "Whether the scope may edit the school profile and logo (admin axis)."
  def can_edit_profile?(scope, %SchoolProfile{} = profile),
    do: Ash.can?({profile, :update}, scope)

  def can_edit_profile?(_scope, nil), do: false

  # `create_user/1` and `promote_to_admin/1` are generated by the
  # `code_interface` defines on the `User` resource above.
  @doc """
  The signed-in user named by a session's `user_id`, or `nil`. Resolving the
  session subject is an authentication interaction (`User`'s bypass).
  """
  def session_user(id) when is_binary(id) do
    case Ash.get(User, id, context: %{private: %{ash_authentication?: true}}) do
      {:ok, user} -> user
      _ -> nil
    end
  end

  def session_user(_id), do: nil

  # --- School profiles -----------------------------------------------------

  def fetch_school_profile(%Scope{} = scope) do
    SchoolProfile
    |> Ash.Query.for_read(
      :for_workspace,
      %{workspace_id: scope.current_workspace.id},
      scope: scope
    )
    |> Ash.read_one()
    |> case do
      {:ok, nil} -> {:error, :not_found}
      result -> result
    end
  end

  def list_unverified_schools(%Scope{} = scope) do
    SchoolProfile |> Ash.Query.for_read(:unverified, %{}, scope: scope) |> Ash.read!()
  end

  # --- School memberships --------------------------------------------------

  def fetch_school_membership(%Scope{} = scope, %User{id: user_id}) do
    SchoolMembership
    |> Ash.Query.for_read(:for_workspace_and_user, %{user_id: user_id}, scope: scope)
    |> Ash.read_one()
    |> case do
      {:ok, nil} -> {:error, :not_a_member}
      {:ok, m} -> {:ok, m}
      error -> error
    end
  end

  def list_members(%Scope{} = scope) do
    SchoolMembership
    |> Ash.Query.for_read(:active_for_workspace, %{}, scope: scope)
    |> Ash.read!()
  end

  def update_member_roles(%Scope{} = scope, %SchoolMembership{} = m, roles) do
    if removing_last_head?(scope, m, roles) do
      {:error, :last_head}
    else
      m |> Ash.Changeset.for_update(:update, %{roles: roles}, scope: scope) |> Ash.update()
    end
  end

  def update_member_status(%Scope{} = scope, %SchoolMembership{} = m, status) do
    m
    |> Ash.Changeset.for_update(:update, %{status: status}, scope: scope)
    |> Ash.update()
  end

  def deactivate_member(%Scope{} = scope, %SchoolMembership{} = m) do
    if :head in m.roles and last_head?(scope, m) do
      {:error, :last_head}
    else
      m |> Ash.Changeset.for_update(:deactivate, %{}, scope: scope) |> Ash.update()
    end
  end

  defp removing_last_head?(%Scope{} = scope, %SchoolMembership{} = m, new_roles) do
    :head in m.roles and :head not in new_roles and last_head?(scope, m)
  end

  # The guard itself lives here (rather than as a resource validation) so
  # callers keep getting the bare `{:error, :last_head}` atom instead of an
  # `%Ash.Error.Invalid{}` — the `other_active_heads` aggregate on
  # `SchoolMembership` does the actual counting.
  defp last_head?(%Scope{} = scope, %SchoolMembership{} = m) do
    m |> Ash.load!(:other_active_heads, scope: scope) |> Map.fetch!(:other_active_heads) == 0
  end

  # --- School invitations --------------------------------------------------

  def invite_member(%Scope{} = scope, %{} = attrs) do
    school = scope.current_workspace
    email = attrs[:email] || attrs["email"]
    roles = attrs[:roles] || attrs["roles"] || [:teacher]
    membership_status = attrs[:membership_status] || attrs["membership_status"]

    with false <- active_member_email?(scope, email),
         {:ok, invitation} <-
           SchoolInvitation
           |> Ash.Changeset.for_create(
             :create,
             %{
               email: email,
               roles: roles,
               membership_status: membership_status,
               invited_by_user_id: scope.current_user && scope.current_user.id,
               token: gen_token(),
               expires_at:
                 DateTime.add(DateTime.utc_now(), 14, :day) |> DateTime.truncate(:second)
             },
             scope: scope
           )
           |> Ash.create() do
      SendSchoolInvitationEmail.send(
        invitation.email,
        school.name,
        invitation.token
      )

      {:ok, invitation}
    else
      true -> {:error, :already_member}
      {:error, error} -> {:error, error}
    end
  end

  def fetch_invitation_by_token(token) do
    SchoolInvitation
    |> Ash.Query.for_read(:by_token, %{token: token})
    |> Ash.read_one()
    |> case do
      {:ok, nil} ->
        {:error, :not_found}

      # The token is the credential (spec §4.2): its bearer may see which
      # school invited them, before they are a member or signed in.
      {:ok, inv} ->
        Ash.load(inv, :workspace, authorize?: false)

      error ->
        error
    end
  end

  def list_pending_invitations(%Scope{} = scope) do
    SchoolInvitation
    |> Ash.Query.for_read(:pending_for_workspace, %{}, scope: scope)
    |> Ash.read!()
  end

  def accept_invitation(%Scope{current_user: %User{} = user} = scope, token) do
    with {:ok, inv} <- fetch_invitation_by_token(token),
         :ok <- check_acceptable(inv),
         :ok <- check_email(inv, user),
         {:ok, _} <-
           inv
           # The invitation's school is the tenant, not the scope's current school.
           |> Ash.Changeset.for_update(:accept, %{}, scope: scope, tenant: inv.workspace_id)
           |> Ash.update() do
      {:ok, inv.workspace}
    else
      {:error, :not_found} -> {:error, :invalid}
      other -> other
    end
  end

  def accept_invitation(%Scope{}, _token), do: {:error, :invalid}

  defp check_acceptable(%SchoolInvitation{status: :pending} = inv) do
    cond do
      inv.expires_at && DateTime.compare(DateTime.utc_now(), inv.expires_at) == :gt ->
        {:error, :expired}

      true ->
        :ok
    end
  end

  defp check_acceptable(_), do: {:error, :invalid}

  defp check_email(%SchoolInvitation{email: email}, %User{email: user_email}) do
    if to_string(email) == to_string(user_email), do: :ok, else: {:error, :email_mismatch}
  end

  defp active_member_email?(%Scope{} = scope, email) do
    scope
    |> list_members()
    |> Enum.any?(fn m -> to_string(m.user.email) == to_string(email) end)
  end

  defp gen_token, do: 24 |> :crypto.strong_rand_bytes() |> Base.url_encode64(padding: false)
end
