defmodule TeacherAssistant.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sequences_subjects_objectives, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :objective, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec

      add :school_id,
          references(:schools,
            column: :id,
            name: "sequences_subjects_objectives_school_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :sequence_id,
          references(:sequences,
            column: :id,
            name: "sequences_subjects_objectives_sequence_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :level_option_subject_id,
          references(:levels_options_subjects,
            column: :id,
            name: "sequences_subjects_objectives_level_option_subject_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(
             :sequences_subjects_objectives,
             [:school_id, :sequence_id, :level_option_subject_id],
             name: "sequences_subjects_objectives_unique_sequence_subject_index"
           )

    alter table(:sequences) do
      remove :objective
    end
  end

  def down do
    alter table(:sequences) do
      add :objective, :text
    end

    drop_if_exists unique_index(
                     :sequences_subjects_objectives,
                     [:school_id, :sequence_id, :level_option_subject_id],
                     name: "sequences_subjects_objectives_unique_sequence_subject_index"
                   )

    drop constraint(
           :sequences_subjects_objectives,
           "sequences_subjects_objectives_school_id_fkey"
         )

    drop constraint(
           :sequences_subjects_objectives,
           "sequences_subjects_objectives_sequence_id_fkey"
         )

    drop constraint(
           :sequences_subjects_objectives,
           "sequences_subjects_objectives_level_option_subject_id_fkey"
         )

    drop table(:sequences_subjects_objectives)
  end
end
