defmodule TeacherAssistant.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:terms, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :start_date, :date
      add :end_date, :date
      add :position, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :school_id, :uuid
      add :academic_year_id, :uuid, null: false
    end

    create table(:subjects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :default_coefficient, :bigint, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :school_id, :uuid
    end

    create table(:students, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :first_name, :citext, null: false
      add :last_name, :citext, null: false
      add :matricule, :text
      add :place_of_birth, :text
      add :date_of_birth, :date
      add :gender, :text, null: false, default: "male"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :school_id, :uuid
    end

    create table(:sequences, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :start_date, :date
      add :end_date, :date
      add :position, :bigint
      add :objective, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :school_id, :uuid
      add :term_id, :uuid, null: false
    end

    create table(:schools, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:terms) do
      modify :school_id,
             references(:schools,
               column: :id,
               name: "terms_school_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:subjects) do
      modify :school_id,
             references(:schools,
               column: :id,
               name: "subjects_school_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:subjects, [:school_id, :name], name: "subjects_unique_name_index")

    alter table(:students) do
      modify :school_id,
             references(:schools,
               column: :id,
               name: "students_school_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:students, [:school_id, :first_name, :last_name, :date_of_birth],
             name: "students_unique_name_and_date_of_birth_index"
           )

    alter table(:sequences) do
      modify :school_id,
             references(:schools,
               column: :id,
               name: "sequences_school_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :term_id,
             references(:terms,
               column: :id,
               name: "sequences_term_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:schools) do
      add :name, :text, null: false
      add :abbreviation, :text
      add :type, :text
      add :sub_system, :text
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:schools, [:name], name: "schools_unique_name_index")

    create table(:school_year_subject_teachers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :school_id,
          references(:schools,
            column: :id,
            name: "school_year_subject_teachers_school_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :classroom_id, :uuid, null: false
      add :level_option_subject_id, :uuid, null: false
      add :teacher_id, :uuid, null: false
    end

    create table(:options, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :citext, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec

      add :school_id,
          references(:schools,
            column: :id,
            name: "options_school_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:options, [:school_id, :name], name: "options_unique_name_index")

    create table(:marks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :score, :decimal, null: false
      add :comment, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec

      add :school_id,
          references(:schools,
            column: :id,
            name: "marks_school_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :student_id,
          references(:students,
            column: :id,
            name: "marks_student_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :classroom_id, :uuid, null: false
      add :sequence_id, :uuid, null: false
      add :level_option_subject_id, :uuid, null: false
    end

    create table(:levels_options_subjects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :coefficient, :bigint, null: false
      add :level_option_id, :uuid, null: false
      add :subject_id, :uuid, null: false
    end

    create table(:levels_options, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:levels_options_subjects) do
      modify :level_option_id,
             references(:levels_options,
               column: :id,
               name: "levels_options_subjects_level_option_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :subject_id,
             references(:subjects,
               column: :id,
               name: "levels_options_subjects_subject_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:levels_options_subjects, [:level_option_id, :subject_id],
             name: "levels_options_subjects_name_index"
           )

    alter table(:levels_options) do
      add :school_id,
          references(:schools,
            column: :id,
            name: "levels_options_school_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :option_id,
          references(:options,
            column: :id,
            name: "levels_options_option_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :level_id, :uuid, null: false
    end

    create table(:levels, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:levels_options) do
      modify :level_id,
             references(:levels,
               column: :id,
               name: "levels_options_level_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:levels_options, [:school_id, :level_id, :option_id],
             name: "levels_options_level_option_index"
           )

    alter table(:levels) do
      add :name, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec

      add :school_id,
          references(:schools,
            column: :id,
            name: "levels_school_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:levels, [:school_id, :name], name: "levels_unique_name_index")

    create table(:classrooms_students, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :archived_at, :utc_datetime_usec

      add :school_id,
          references(:schools,
            column: :id,
            name: "classrooms_students_school_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :classroom_id, :uuid, null: false
      add :student_id, :uuid, null: false
    end

    create table(:classrooms, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:school_year_subject_teachers) do
      modify :classroom_id,
             references(:classrooms,
               column: :id,
               name: "school_year_subject_teachers_classroom_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :level_option_subject_id,
             references(:levels_options_subjects,
               column: :id,
               name: "school_year_subject_teachers_level_option_subject_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :teacher_id,
             references(:users,
               column: :id,
               name: "school_year_subject_teachers_teacher_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(
             :school_year_subject_teachers,
             [:school_id, :classroom_id, :level_option_subject_id, :teacher_id],
             name: "school_year_subject_teachers_unique_assignment_index"
           )

    alter table(:marks) do
      modify :classroom_id,
             references(:classrooms,
               column: :id,
               name: "marks_classroom_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :sequence_id,
             references(:sequences,
               column: :id,
               name: "marks_sequence_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :level_option_subject_id,
             references(:levels_options_subjects,
               column: :id,
               name: "marks_level_option_subject_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:marks, [:school_id, :student_id, :level_option_subject_id, :sequence_id],
             name: "marks_unique_mark_index"
           )

    alter table(:classrooms_students) do
      modify :classroom_id,
             references(:classrooms,
               column: :id,
               name: "classrooms_students_classroom_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :student_id,
             references(:students,
               column: :id,
               name: "classrooms_students_student_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:classrooms_students, [:school_id, :classroom_id, :student_id],
             name: "classrooms_students_classroom_student_index"
           )

    alter table(:classrooms) do
      add :archived_at, :utc_datetime_usec

      add :school_id,
          references(:schools,
            column: :id,
            name: "classrooms_school_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :academic_year_id, :uuid, null: false
      add :level_option_id, :uuid, null: false
    end

    create table(:attendances, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :date, :date, null: false
      add :status, :text, null: false, default: "present"
      add :comment, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec

      add :school_id,
          references(:schools,
            column: :id,
            name: "attendances_school_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :student_id,
          references(:students,
            column: :id,
            name: "attendances_student_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :classroom_id,
          references(:classrooms,
            column: :id,
            name: "attendances_classroom_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:attendances, [:school_id, :student_id, :classroom_id, :date],
             name: "attendances_unique_attendance_index"
           )

    create table(:academic_years, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:terms) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "terms_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:terms, [:school_id, :name, :academic_year_id],
             name: "terms_unique_name_index"
           )

    alter table(:classrooms) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "classrooms_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :level_option_id,
             references(:levels_options,
               column: :id,
               name: "classrooms_level_option_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:classrooms, [:school_id, :academic_year_id, :level_option_id],
             name: "classrooms_name_index"
           )

    alter table(:academic_years) do
      add :name, :text, null: false
      add :description, :text
      add :start_date, :date, null: false
      add :end_date, :date, null: false
      add :active, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec

      add :school_id,
          references(:schools,
            column: :id,
            name: "academic_years_school_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:academic_years, [:school_id, :name],
             name: "academic_years_unique_name_index"
           )
  end

  def down do
    drop_if_exists unique_index(:academic_years, [:school_id, :name],
                     name: "academic_years_unique_name_index"
                   )

    drop constraint(:academic_years, "academic_years_school_id_fkey")

    alter table(:academic_years) do
      remove :school_id
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :active
      remove :end_date
      remove :start_date
      remove :description
      remove :name
    end

    drop_if_exists unique_index(:classrooms, [:school_id, :academic_year_id, :level_option_id],
                     name: "classrooms_name_index"
                   )

    drop constraint(:classrooms, "classrooms_academic_year_id_fkey")

    drop constraint(:classrooms, "classrooms_level_option_id_fkey")

    alter table(:classrooms) do
      modify :level_option_id, :uuid
      modify :academic_year_id, :uuid
    end

    drop_if_exists unique_index(:terms, [:school_id, :name, :academic_year_id],
                     name: "terms_unique_name_index"
                   )

    drop constraint(:terms, "terms_academic_year_id_fkey")

    alter table(:terms) do
      modify :academic_year_id, :uuid
    end

    drop table(:academic_years)

    drop_if_exists unique_index(:attendances, [:school_id, :student_id, :classroom_id, :date],
                     name: "attendances_unique_attendance_index"
                   )

    drop constraint(:attendances, "attendances_school_id_fkey")

    drop constraint(:attendances, "attendances_student_id_fkey")

    drop constraint(:attendances, "attendances_classroom_id_fkey")

    drop table(:attendances)

    drop constraint(:classrooms, "classrooms_school_id_fkey")

    alter table(:classrooms) do
      remove :level_option_id
      remove :academic_year_id
      remove :school_id
      remove :archived_at
    end

    drop_if_exists unique_index(:classrooms_students, [:school_id, :classroom_id, :student_id],
                     name: "classrooms_students_classroom_student_index"
                   )

    drop constraint(:classrooms_students, "classrooms_students_classroom_id_fkey")

    drop constraint(:classrooms_students, "classrooms_students_student_id_fkey")

    alter table(:classrooms_students) do
      modify :student_id, :uuid
      modify :classroom_id, :uuid
    end

    drop_if_exists unique_index(
                     :marks,
                     [:school_id, :student_id, :level_option_subject_id, :sequence_id],
                     name: "marks_unique_mark_index"
                   )

    drop constraint(:marks, "marks_classroom_id_fkey")

    drop constraint(:marks, "marks_sequence_id_fkey")

    drop constraint(:marks, "marks_level_option_subject_id_fkey")

    alter table(:marks) do
      modify :level_option_subject_id, :uuid
      modify :sequence_id, :uuid
      modify :classroom_id, :uuid
    end

    drop_if_exists unique_index(
                     :school_year_subject_teachers,
                     [:school_id, :classroom_id, :level_option_subject_id, :teacher_id],
                     name: "school_year_subject_teachers_unique_assignment_index"
                   )

    drop constraint(
           :school_year_subject_teachers,
           "school_year_subject_teachers_classroom_id_fkey"
         )

    drop constraint(
           :school_year_subject_teachers,
           "school_year_subject_teachers_level_option_subject_id_fkey"
         )

    drop constraint(:school_year_subject_teachers, "school_year_subject_teachers_teacher_id_fkey")

    alter table(:school_year_subject_teachers) do
      modify :teacher_id, :uuid
      modify :level_option_subject_id, :uuid
      modify :classroom_id, :uuid
    end

    drop table(:classrooms)

    drop constraint(:classrooms_students, "classrooms_students_school_id_fkey")

    drop table(:classrooms_students)

    drop_if_exists unique_index(:levels, [:school_id, :name], name: "levels_unique_name_index")

    drop constraint(:levels, "levels_school_id_fkey")

    alter table(:levels) do
      remove :school_id
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :name
    end

    drop_if_exists unique_index(:levels_options, [:school_id, :level_id, :option_id],
                     name: "levels_options_level_option_index"
                   )

    drop constraint(:levels_options, "levels_options_level_id_fkey")

    alter table(:levels_options) do
      modify :level_id, :uuid
    end

    drop table(:levels)

    drop constraint(:levels_options, "levels_options_school_id_fkey")

    drop constraint(:levels_options, "levels_options_option_id_fkey")

    alter table(:levels_options) do
      remove :level_id
      remove :option_id
      remove :school_id
    end

    drop_if_exists unique_index(:levels_options_subjects, [:level_option_id, :subject_id],
                     name: "levels_options_subjects_name_index"
                   )

    drop constraint(:levels_options_subjects, "levels_options_subjects_level_option_id_fkey")

    drop constraint(:levels_options_subjects, "levels_options_subjects_subject_id_fkey")

    alter table(:levels_options_subjects) do
      modify :subject_id, :uuid
      modify :level_option_id, :uuid
    end

    drop table(:levels_options)

    drop table(:levels_options_subjects)

    drop constraint(:marks, "marks_school_id_fkey")

    drop constraint(:marks, "marks_student_id_fkey")

    drop table(:marks)

    drop_if_exists unique_index(:options, [:school_id, :name], name: "options_unique_name_index")

    drop constraint(:options, "options_school_id_fkey")

    drop table(:options)

    drop constraint(:school_year_subject_teachers, "school_year_subject_teachers_school_id_fkey")

    drop table(:school_year_subject_teachers)

    drop_if_exists unique_index(:schools, [:name], name: "schools_unique_name_index")

    alter table(:schools) do
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :sub_system
      remove :type
      remove :abbreviation
      remove :name
    end

    drop constraint(:sequences, "sequences_school_id_fkey")

    drop constraint(:sequences, "sequences_term_id_fkey")

    alter table(:sequences) do
      modify :term_id, :uuid
      modify :school_id, :uuid
    end

    drop_if_exists unique_index(:students, [:school_id, :first_name, :last_name, :date_of_birth],
                     name: "students_unique_name_and_date_of_birth_index"
                   )

    drop constraint(:students, "students_school_id_fkey")

    alter table(:students) do
      modify :school_id, :uuid
    end

    drop_if_exists unique_index(:subjects, [:school_id, :name],
                     name: "subjects_unique_name_index"
                   )

    drop constraint(:subjects, "subjects_school_id_fkey")

    alter table(:subjects) do
      modify :school_id, :uuid
    end

    drop constraint(:terms, "terms_school_id_fkey")

    alter table(:terms) do
      modify :school_id, :uuid
    end

    drop table(:schools)

    drop table(:sequences)

    drop table(:students)

    drop table(:subjects)

    drop table(:terms)
  end
end
