defmodule TeacherAssistant.Repo.Migrations.UnifyWorkspace do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`, then
  hand-edited to use renames instead of drop+recreate so existing dev data
  (the `personal_workspaces` table and the 5 `personal_workspace_id` FK
  columns) is preserved.
  """

  use Ecto.Migration

  def up do
    rename table(:personal_workspaces), to: table(:workspaces)

    alter table(:workspaces) do
      add :kind, :text, null: false, default: "personal"
      modify :owner_user_id, :uuid, null: true
    end

    execute "ALTER TABLE workspaces RENAME CONSTRAINT personal_workspaces_pkey TO workspaces_pkey"

    execute "ALTER INDEX personal_workspaces_unique_owner_user_index RENAME TO workspaces_unique_owner_user_index"

    execute "ALTER TABLE workspaces RENAME CONSTRAINT personal_workspaces_owner_user_id_fkey TO workspaces_owner_user_id_fkey"

    rename table(:teaching_log_entries), :personal_workspace_id, to: :workspace_id

    execute "ALTER TABLE teaching_log_entries RENAME CONSTRAINT teaching_log_entries_personal_workspace_id_fkey TO teaching_log_entries_workspace_id_fkey"

    rename table(:teaching_contexts), :personal_workspace_id, to: :workspace_id

    execute "ALTER TABLE teaching_contexts RENAME CONSTRAINT teaching_contexts_personal_workspace_id_fkey TO teaching_contexts_workspace_id_fkey"

    drop_if_exists unique_index(
                     :teaching_contexts,
                     [:personal_workspace_id, :academic_year_id, :subject, :level, :serie],
                     name: "teaching_contexts_unique_context_index"
                   )

    create unique_index(
             :teaching_contexts,
             [:workspace_id, :academic_year_id, :subject, :level, :serie],
             name: "teaching_contexts_unique_context_index"
           )

    rename table(:progression_plans), :personal_workspace_id, to: :workspace_id

    execute "ALTER TABLE progression_plans RENAME CONSTRAINT progression_plans_personal_workspace_id_fkey TO progression_plans_workspace_id_fkey"

    rename table(:class_groups), :personal_workspace_id, to: :workspace_id

    execute "ALTER TABLE class_groups RENAME CONSTRAINT class_groups_personal_workspace_id_fkey TO class_groups_workspace_id_fkey"

    drop_if_exists unique_index(
                     :class_groups,
                     [:personal_workspace_id, :academic_year_id, :label],
                     name: "class_groups_unique_class_group_index"
                   )

    create unique_index(:class_groups, [:workspace_id, :academic_year_id, :label],
             name: "class_groups_unique_class_group_index"
           )

    rename table(:academic_years), :personal_workspace_id, to: :workspace_id

    execute "ALTER TABLE academic_years RENAME CONSTRAINT academic_years_personal_workspace_id_fkey TO academic_years_workspace_id_fkey"

    drop_if_exists unique_index(:academic_years, [:personal_workspace_id, :name],
                     name: "academic_years_unique_workspace_year_index"
                   )

    create unique_index(:academic_years, [:workspace_id, :name],
             name: "academic_years_unique_workspace_year_index"
           )
  end

  def down do
    drop_if_exists unique_index(:academic_years, [:workspace_id, :name],
                     name: "academic_years_unique_workspace_year_index"
                   )

    create unique_index(:academic_years, [:personal_workspace_id, :name],
             name: "academic_years_unique_workspace_year_index"
           )

    execute "ALTER TABLE academic_years RENAME CONSTRAINT academic_years_workspace_id_fkey TO academic_years_personal_workspace_id_fkey"

    rename table(:academic_years), :workspace_id, to: :personal_workspace_id

    drop_if_exists unique_index(:class_groups, [:workspace_id, :academic_year_id, :label],
                     name: "class_groups_unique_class_group_index"
                   )

    create unique_index(:class_groups, [:personal_workspace_id, :academic_year_id, :label],
             name: "class_groups_unique_class_group_index"
           )

    execute "ALTER TABLE class_groups RENAME CONSTRAINT class_groups_workspace_id_fkey TO class_groups_personal_workspace_id_fkey"

    rename table(:class_groups), :workspace_id, to: :personal_workspace_id

    execute "ALTER TABLE progression_plans RENAME CONSTRAINT progression_plans_workspace_id_fkey TO progression_plans_personal_workspace_id_fkey"

    rename table(:progression_plans), :workspace_id, to: :personal_workspace_id

    drop_if_exists unique_index(
                     :teaching_contexts,
                     [:workspace_id, :academic_year_id, :subject, :level, :serie],
                     name: "teaching_contexts_unique_context_index"
                   )

    create unique_index(
             :teaching_contexts,
             [:personal_workspace_id, :academic_year_id, :subject, :level, :serie],
             name: "teaching_contexts_unique_context_index"
           )

    execute "ALTER TABLE teaching_contexts RENAME CONSTRAINT teaching_contexts_workspace_id_fkey TO teaching_contexts_personal_workspace_id_fkey"

    rename table(:teaching_contexts), :workspace_id, to: :personal_workspace_id

    execute "ALTER TABLE teaching_log_entries RENAME CONSTRAINT teaching_log_entries_workspace_id_fkey TO teaching_log_entries_personal_workspace_id_fkey"

    rename table(:teaching_log_entries), :workspace_id, to: :personal_workspace_id

    execute "ALTER TABLE workspaces RENAME CONSTRAINT workspaces_owner_user_id_fkey TO personal_workspaces_owner_user_id_fkey"

    execute "ALTER INDEX workspaces_unique_owner_user_index RENAME TO personal_workspaces_unique_owner_user_index"

    execute "ALTER TABLE workspaces RENAME CONSTRAINT workspaces_pkey TO personal_workspaces_pkey"

    alter table(:workspaces) do
      remove :kind
      modify :owner_user_id, :uuid, null: false
    end

    rename table(:workspaces), to: table(:personal_workspaces)
  end
end
