defmodule TeacherAssistant.Repo.Migrations.DisciplineFeesTenancy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:conduct_marks, [:enrollment_id, :sequence_id],
                     name: "conduct_marks_unique_conduct_mark_index"
                   )

    create unique_index(:conduct_marks, [:workspace_id, :enrollment_id, :sequence_id],
             name: "conduct_marks_unique_conduct_mark_index"
           )

    drop_if_exists index(:conduct_marks, [:enrollment_id])

    create index(:conduct_marks, [:workspace_id, :enrollment_id])

    drop_if_exists index(:conduct_marks, [:sequence_id])

    create index(:conduct_marks, [:workspace_id, :sequence_id])

    drop_if_exists index(:conduct_marks, [:workspace_id])

    create index(:conduct_marks, [:workspace_id])

    drop_if_exists unique_index(:fee_adjustments, [:enrollment_id],
                     name: "fee_adjustments_unique_adjustment_index"
                   )

    create unique_index(:fee_adjustments, [:workspace_id, :enrollment_id],
             name: "fee_adjustments_unique_adjustment_index"
           )

    drop_if_exists index(:fee_adjustments, [:enrollment_id])

    create index(:fee_adjustments, [:workspace_id, :enrollment_id])

    drop_if_exists index(:fee_adjustments, [:workspace_id])

    create index(:fee_adjustments, [:workspace_id])

    drop_if_exists index(:fee_tranches, [:class_group_id])

    create index(:fee_tranches, [:workspace_id, :class_group_id])

    drop_if_exists index(:fee_tranches, [:workspace_id])

    create index(:fee_tranches, [:workspace_id])

    drop_if_exists index(:payments, [:enrollment_id])

    create index(:payments, [:workspace_id, :enrollment_id])

    drop_if_exists index(:payments, [:workspace_id])

    create index(:payments, [:workspace_id])

    drop_if_exists index(:sanction_entries, [:enrollment_id])

    create index(:sanction_entries, [:workspace_id, :enrollment_id])

    drop_if_exists index(:sanction_entries, [:workspace_id])

    create index(:sanction_entries, [:workspace_id])
  end

  def down do
    drop_if_exists index(:sanction_entries, [:workspace_id])

    create index(:sanction_entries, [:workspace_id])

    drop_if_exists index(:sanction_entries, [:workspace_id, :enrollment_id])

    create index(:sanction_entries, [:enrollment_id])

    drop_if_exists index(:payments, [:workspace_id])

    create index(:payments, [:workspace_id])

    drop_if_exists index(:payments, [:workspace_id, :enrollment_id])

    create index(:payments, [:enrollment_id])

    drop_if_exists index(:fee_tranches, [:workspace_id])

    create index(:fee_tranches, [:workspace_id])

    drop_if_exists index(:fee_tranches, [:workspace_id, :class_group_id])

    create index(:fee_tranches, [:class_group_id])

    drop_if_exists index(:fee_adjustments, [:workspace_id])

    create index(:fee_adjustments, [:workspace_id])

    drop_if_exists index(:fee_adjustments, [:workspace_id, :enrollment_id])

    create index(:fee_adjustments, [:enrollment_id])

    drop_if_exists unique_index(:fee_adjustments, [:workspace_id, :enrollment_id],
                     name: "fee_adjustments_unique_adjustment_index"
                   )

    create unique_index(:fee_adjustments, [:enrollment_id],
             name: "fee_adjustments_unique_adjustment_index"
           )

    drop_if_exists index(:conduct_marks, [:workspace_id])

    create index(:conduct_marks, [:workspace_id])

    drop_if_exists index(:conduct_marks, [:workspace_id, :sequence_id])

    create index(:conduct_marks, [:sequence_id])

    drop_if_exists index(:conduct_marks, [:workspace_id, :enrollment_id])

    create index(:conduct_marks, [:enrollment_id])

    drop_if_exists unique_index(:conduct_marks, [:workspace_id, :enrollment_id, :sequence_id],
                     name: "conduct_marks_unique_conduct_mark_index"
                   )

    create unique_index(:conduct_marks, [:enrollment_id, :sequence_id],
             name: "conduct_marks_unique_conduct_mark_index"
           )
  end
end
