defmodule TeacherAssistant.Repo.Migrations.AddContextTargetsAndModuleCredit do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:teaching_contexts) do
      add :annual_hours, :decimal
      add :target_module_count, :bigint
      add :target_lesson_count, :bigint
    end

    alter table(:progression_modules) do
      add :credit_hours, :decimal
    end
  end

  def down do
    alter table(:progression_modules) do
      remove :credit_hours
    end

    alter table(:teaching_contexts) do
      remove :target_lesson_count
      remove :target_module_count
      remove :annual_hours
    end
  end
end
