defmodule TeacherAssistant.Repo.Migrations.MigrateResources7 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:progression_entries) do
      modify :entry_type, :text, null: false
    end
  end

  def down do
    alter table(:progression_entries) do
      modify :entry_type, :text, null: true
    end
  end
end
