defmodule TeacherAssistant.Repo.Migrations.AddLessonPlansAndSteps do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:lesson_steps, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :position, :bigint, null: false
      add :etape, :text
      add :duration_minutes, :bigint
      add :contenus, :text
      add :supports, :text
      add :activites, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :lesson_plan_id, :uuid, null: false
    end

    create table(:lesson_plans, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:lesson_steps) do
      modify :lesson_plan_id,
             references(:lesson_plans,
               column: :id,
               name: "lesson_steps_lesson_plan_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:lesson_plans) do
      add :lesson_date, :date
      add :duration_minutes, :bigint, default: 55
      add :titre, :text
      add :competence_attendue, :text
      add :situation_probleme, :text
      add :objectifs, :text
      add :supports, :text
      add :prerequis, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :progression_entry_id,
          references(:progression_entries,
            column: :id,
            name: "lesson_plans_progression_entry_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:lesson_plans, [:progression_entry_id],
             name: "lesson_plans_unique_entry_index"
           )
  end

  def down do
    drop constraint(:lesson_plans, "lesson_plans_progression_entry_id_fkey")

    drop_if_exists unique_index(:lesson_plans, [:progression_entry_id],
                     name: "lesson_plans_unique_entry_index"
                   )

    alter table(:lesson_plans) do
      remove :progression_entry_id
      remove :updated_at
      remove :inserted_at
      remove :prerequis
      remove :supports
      remove :objectifs
      remove :situation_probleme
      remove :competence_attendue
      remove :titre
      remove :duration_minutes
      remove :lesson_date
    end

    drop constraint(:lesson_steps, "lesson_steps_lesson_plan_id_fkey")

    alter table(:lesson_steps) do
      modify :lesson_plan_id, :uuid
    end

    drop table(:lesson_plans)

    drop table(:lesson_steps)
  end
end
