defmodule TeacherAssistant.Repo.Migrations.AddPayment do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:payments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :amount, :bigint, null: false
      add :paid_on, :date, null: false
      add :method, :text, null: false
      add :reference, :text
      add :note, :text
      add :recorded_by_user_id, :uuid
      add :workspace_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :enrollment_id,
          references(:enrollments,
            column: :id,
            name: "payments_enrollment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end
  end

  def down do
    drop constraint(:payments, "payments_enrollment_id_fkey")

    drop table(:payments)
  end
end
