defmodule TeacherAssistant.Repo.Migrations.WorkspaceFks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:academic_years, "academic_years_workspace_id_fkey")

    alter table(:academic_years) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "academic_years_workspace_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:academic_years, [:workspace_id])

    alter table(:assessments) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "assessments_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:assessments, [:teaching_context_id])

    create index(:assessments, [:sequence_id])

    create index(:assessments, [:workspace_id])

    alter table(:attendance_entries) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "attendance_entries_workspace_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:attendance_entries, [:enrollment_id])

    create index(:attendance_entries, [:period_id])

    create index(:attendance_entries, [:teaching_context_id])

    create index(:attendance_entries, [:workspace_id])

    drop constraint(:class_groups, "class_groups_workspace_id_fkey")

    alter table(:class_groups) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "class_groups_workspace_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:class_groups, [:form_master_user_id])

    create index(:class_groups, [:workspace_id])

    create index(:class_groups, [:academic_year_id])

    drop constraint(:combined_courses, "combined_courses_workspace_id_fkey")

    alter table(:combined_courses) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "combined_courses_workspace_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:combined_courses, [:teacher_user_id])

    create index(:combined_courses, [:workspace_id])

    create index(:combined_courses, [:academic_year_id])

    alter table(:conduct_marks) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "conduct_marks_workspace_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:conduct_marks, [:enrollment_id])

    create index(:conduct_marks, [:sequence_id])

    create index(:conduct_marks, [:workspace_id])

    drop constraint(:enrollments, "enrollments_workspace_id_fkey")

    alter table(:enrollments) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "enrollments_workspace_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:enrollments, [:student_id])

    create index(:enrollments, [:class_group_id])

    create index(:enrollments, [:academic_year_id])

    create index(:enrollments, [:workspace_id])

    alter table(:fee_adjustments) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "fee_adjustments_workspace_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:fee_adjustments, [:enrollment_id])

    create index(:fee_adjustments, [:workspace_id])

    alter table(:fee_tranches) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "fee_tranches_workspace_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:fee_tranches, [:class_group_id])

    create index(:fee_tranches, [:workspace_id])

    alter table(:lesson_plans) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "lesson_plans_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:lesson_plans, [:progression_entry_id])

    create index(:lesson_plans, [:workspace_id])

    alter table(:lesson_steps) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "lesson_steps_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:lesson_steps, [:lesson_plan_id])

    create index(:lesson_steps, [:workspace_id])

    alter table(:marks) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "marks_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:marks, [:assessment_id])

    create index(:marks, [:student_id])

    create index(:marks, [:workspace_id])

    alter table(:payments) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "payments_workspace_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:payments, [:enrollment_id])

    create index(:payments, [:workspace_id])

    drop constraint(:periods, "periods_workspace_id_fkey")

    alter table(:periods) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "periods_workspace_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:periods, [:workspace_id])

    alter table(:progression_entries) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "progression_entries_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:progression_entries, [:progression_plan_id])

    create index(:progression_entries, [:sequence_id])

    create index(:progression_entries, [:progression_module_id])

    create index(:progression_entries, [:workspace_id])

    alter table(:progression_modules) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "progression_modules_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:progression_modules, [:progression_plan_id])

    create index(:progression_modules, [:sequence_id])

    create index(:progression_modules, [:workspace_id])

    drop constraint(:progression_plans, "progression_plans_workspace_id_fkey")

    alter table(:progression_plans) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "progression_plans_workspace_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:progression_plans, [:combined_course_id])

    create index(:progression_plans, [:teaching_context_id])

    create index(:progression_plans, [:academic_year_id])

    create index(:progression_plans, [:workspace_id])

    alter table(:sanction_entries) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "sanction_entries_workspace_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:sanction_entries, [:enrollment_id])

    create index(:sanction_entries, [:workspace_id])

    drop constraint(:school_invitations, "school_invitations_workspace_id_fkey")

    alter table(:school_invitations) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "school_invitations_workspace_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:school_invitations, [:workspace_id])

    create index(:school_invitations, [:invited_by_user_id])

    drop constraint(:school_memberships, "school_memberships_workspace_id_fkey")

    alter table(:school_memberships) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "school_memberships_workspace_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:school_memberships, [:workspace_id])

    create index(:school_memberships, [:user_id])

    alter table(:sequences) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "sequences_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:sequences, [:term_id])

    create index(:sequences, [:workspace_id])

    drop constraint(:students, "students_workspace_id_fkey")

    alter table(:students) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "students_workspace_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:students, [:workspace_id])

    drop constraint(:subjects, "subjects_workspace_id_fkey")

    alter table(:subjects) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "subjects_workspace_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:subjects, [:workspace_id])

    drop constraint(:teaching_contexts, "teaching_contexts_workspace_id_fkey")

    alter table(:teaching_contexts) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "teaching_contexts_workspace_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:teaching_contexts, [:combined_course_id])

    create index(:teaching_contexts, [:workspace_id])

    create index(:teaching_contexts, [:academic_year_id])

    create index(:teaching_contexts, [:class_group_id])

    create index(:teaching_contexts, [:teacher_user_id])

    drop constraint(:teaching_log_entries, "teaching_log_entries_workspace_id_fkey")

    alter table(:teaching_log_entries) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "teaching_log_entries_workspace_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:teaching_log_entries, [:workspace_id])

    create index(:teaching_log_entries, [:progression_entry_id])

    alter table(:terms) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "terms_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:terms, [:academic_year_id])

    create index(:terms, [:workspace_id])

    alter table(:timetable_slots) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "timetable_slots_workspace_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:timetable_slots, [:class_group_id])

    create index(:timetable_slots, [:teaching_context_id])

    create index(:timetable_slots, [:period_id])

    create index(:timetable_slots, [:workspace_id])
  end

  def down do
    drop_if_exists index(:timetable_slots, [:workspace_id])

    drop_if_exists index(:timetable_slots, [:period_id])

    drop_if_exists index(:timetable_slots, [:teaching_context_id])

    drop_if_exists index(:timetable_slots, [:class_group_id])

    drop constraint(:timetable_slots, "timetable_slots_workspace_id_fkey")

    alter table(:timetable_slots) do
      modify :workspace_id, :uuid
    end

    drop_if_exists index(:terms, [:workspace_id])

    drop_if_exists index(:terms, [:academic_year_id])

    drop constraint(:terms, "terms_workspace_id_fkey")

    alter table(:terms) do
      remove :workspace_id
    end

    drop_if_exists index(:teaching_log_entries, [:progression_entry_id])

    drop_if_exists index(:teaching_log_entries, [:workspace_id])

    drop constraint(:teaching_log_entries, "teaching_log_entries_workspace_id_fkey")

    alter table(:teaching_log_entries) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "teaching_log_entries_workspace_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:teaching_contexts, [:teacher_user_id])

    drop_if_exists index(:teaching_contexts, [:class_group_id])

    drop_if_exists index(:teaching_contexts, [:academic_year_id])

    drop_if_exists index(:teaching_contexts, [:workspace_id])

    drop_if_exists index(:teaching_contexts, [:combined_course_id])

    drop constraint(:teaching_contexts, "teaching_contexts_workspace_id_fkey")

    alter table(:teaching_contexts) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "teaching_contexts_workspace_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:subjects, [:workspace_id])

    drop constraint(:subjects, "subjects_workspace_id_fkey")

    alter table(:subjects) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "subjects_workspace_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:students, [:workspace_id])

    drop constraint(:students, "students_workspace_id_fkey")

    alter table(:students) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "students_workspace_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:sequences, [:workspace_id])

    drop_if_exists index(:sequences, [:term_id])

    drop constraint(:sequences, "sequences_workspace_id_fkey")

    alter table(:sequences) do
      remove :workspace_id
    end

    drop_if_exists index(:school_memberships, [:user_id])

    drop_if_exists index(:school_memberships, [:workspace_id])

    drop constraint(:school_memberships, "school_memberships_workspace_id_fkey")

    alter table(:school_memberships) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "school_memberships_workspace_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:school_invitations, [:invited_by_user_id])

    drop_if_exists index(:school_invitations, [:workspace_id])

    drop constraint(:school_invitations, "school_invitations_workspace_id_fkey")

    alter table(:school_invitations) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "school_invitations_workspace_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:sanction_entries, [:workspace_id])

    drop_if_exists index(:sanction_entries, [:enrollment_id])

    drop constraint(:sanction_entries, "sanction_entries_workspace_id_fkey")

    alter table(:sanction_entries) do
      modify :workspace_id, :uuid
    end

    drop_if_exists index(:progression_plans, [:workspace_id])

    drop_if_exists index(:progression_plans, [:academic_year_id])

    drop_if_exists index(:progression_plans, [:teaching_context_id])

    drop_if_exists index(:progression_plans, [:combined_course_id])

    drop constraint(:progression_plans, "progression_plans_workspace_id_fkey")

    alter table(:progression_plans) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "progression_plans_workspace_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:progression_modules, [:workspace_id])

    drop_if_exists index(:progression_modules, [:sequence_id])

    drop_if_exists index(:progression_modules, [:progression_plan_id])

    drop constraint(:progression_modules, "progression_modules_workspace_id_fkey")

    alter table(:progression_modules) do
      remove :workspace_id
    end

    drop_if_exists index(:progression_entries, [:workspace_id])

    drop_if_exists index(:progression_entries, [:progression_module_id])

    drop_if_exists index(:progression_entries, [:sequence_id])

    drop_if_exists index(:progression_entries, [:progression_plan_id])

    drop constraint(:progression_entries, "progression_entries_workspace_id_fkey")

    alter table(:progression_entries) do
      remove :workspace_id
    end

    drop_if_exists index(:periods, [:workspace_id])

    drop constraint(:periods, "periods_workspace_id_fkey")

    alter table(:periods) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "periods_workspace_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:payments, [:workspace_id])

    drop_if_exists index(:payments, [:enrollment_id])

    drop constraint(:payments, "payments_workspace_id_fkey")

    alter table(:payments) do
      modify :workspace_id, :uuid
    end

    drop_if_exists index(:marks, [:workspace_id])

    drop_if_exists index(:marks, [:student_id])

    drop_if_exists index(:marks, [:assessment_id])

    drop constraint(:marks, "marks_workspace_id_fkey")

    alter table(:marks) do
      remove :workspace_id
    end

    drop_if_exists index(:lesson_steps, [:workspace_id])

    drop_if_exists index(:lesson_steps, [:lesson_plan_id])

    drop constraint(:lesson_steps, "lesson_steps_workspace_id_fkey")

    alter table(:lesson_steps) do
      remove :workspace_id
    end

    drop_if_exists index(:lesson_plans, [:workspace_id])

    drop_if_exists index(:lesson_plans, [:progression_entry_id])

    drop constraint(:lesson_plans, "lesson_plans_workspace_id_fkey")

    alter table(:lesson_plans) do
      remove :workspace_id
    end

    drop_if_exists index(:fee_tranches, [:workspace_id])

    drop_if_exists index(:fee_tranches, [:class_group_id])

    drop constraint(:fee_tranches, "fee_tranches_workspace_id_fkey")

    alter table(:fee_tranches) do
      modify :workspace_id, :uuid
    end

    drop_if_exists index(:fee_adjustments, [:workspace_id])

    drop_if_exists index(:fee_adjustments, [:enrollment_id])

    drop constraint(:fee_adjustments, "fee_adjustments_workspace_id_fkey")

    alter table(:fee_adjustments) do
      modify :workspace_id, :uuid
    end

    drop_if_exists index(:enrollments, [:workspace_id])

    drop_if_exists index(:enrollments, [:academic_year_id])

    drop_if_exists index(:enrollments, [:class_group_id])

    drop_if_exists index(:enrollments, [:student_id])

    drop constraint(:enrollments, "enrollments_workspace_id_fkey")

    alter table(:enrollments) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "enrollments_workspace_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:conduct_marks, [:workspace_id])

    drop_if_exists index(:conduct_marks, [:sequence_id])

    drop_if_exists index(:conduct_marks, [:enrollment_id])

    drop constraint(:conduct_marks, "conduct_marks_workspace_id_fkey")

    alter table(:conduct_marks) do
      modify :workspace_id, :uuid
    end

    drop_if_exists index(:combined_courses, [:academic_year_id])

    drop_if_exists index(:combined_courses, [:workspace_id])

    drop_if_exists index(:combined_courses, [:teacher_user_id])

    drop constraint(:combined_courses, "combined_courses_workspace_id_fkey")

    alter table(:combined_courses) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "combined_courses_workspace_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:class_groups, [:academic_year_id])

    drop_if_exists index(:class_groups, [:workspace_id])

    drop_if_exists index(:class_groups, [:form_master_user_id])

    drop constraint(:class_groups, "class_groups_workspace_id_fkey")

    alter table(:class_groups) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "class_groups_workspace_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:attendance_entries, [:workspace_id])

    drop_if_exists index(:attendance_entries, [:teaching_context_id])

    drop_if_exists index(:attendance_entries, [:period_id])

    drop_if_exists index(:attendance_entries, [:enrollment_id])

    drop constraint(:attendance_entries, "attendance_entries_workspace_id_fkey")

    alter table(:attendance_entries) do
      modify :workspace_id, :uuid
    end

    drop_if_exists index(:assessments, [:workspace_id])

    drop_if_exists index(:assessments, [:sequence_id])

    drop_if_exists index(:assessments, [:teaching_context_id])

    drop constraint(:assessments, "assessments_workspace_id_fkey")

    alter table(:assessments) do
      remove :workspace_id
    end

    drop_if_exists index(:academic_years, [:workspace_id])

    drop constraint(:academic_years, "academic_years_workspace_id_fkey")

    alter table(:academic_years) do
      modify :workspace_id,
             references(:workspaces,
               column: :id,
               name: "academic_years_workspace_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
