defmodule TeacherAssistant.Repo.Migrations.ConstraintsAndIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create constraint(:academic_years, :academic_years_dates_ordered_check,
             check: """
               end_date > start_date
             """
           )

    create index(:academic_years, [:workspace_id],
             name: "academic_years_one_active_per_workspace",
             unique: true,
             where: "active"
           )

    create index(:attendance_entries, [:enrollment_id, :date])

    create index(:attendance_entries, [:workspace_id, :date])

    create constraint(:conduct_marks, :conduct_marks_value_in_range_check,
             check: """
               value >= 0 AND value <= 20
             """
           )

    create constraint(:fee_adjustments, :fee_adjustments_amount_non_zero_check,
             check: """
               amount <> 0
             """
           )

    create constraint(:fee_tranches, :fee_tranches_amount_non_negative_check,
             check: """
               amount >= 0
             """
           )

    create constraint(:marks, :marks_score_non_negative_check,
             check: """
               score IS NULL OR score >= 0
             """
           )

    create constraint(:payments, :payments_amount_positive_check,
             check: """
               amount > 0
             """
           )

    create index(:progression_entries, [:progression_module_id, :position])

    create constraint(:sequences, :sequences_dates_ordered_check,
             check: """
               end_date >= start_date
             """
           )

    create index(:timetable_slots, [:workspace_id, :teaching_context_id])
  end

  def down do
    drop_if_exists index(:timetable_slots, [:workspace_id, :teaching_context_id])

    drop_if_exists constraint(:sequences, :sequences_dates_ordered_check)

    drop_if_exists index(:progression_entries, [:progression_module_id, :position])

    drop_if_exists constraint(:payments, :payments_amount_positive_check)

    drop_if_exists constraint(:marks, :marks_score_non_negative_check)

    drop_if_exists constraint(:fee_tranches, :fee_tranches_amount_non_negative_check)

    drop_if_exists constraint(:fee_adjustments, :fee_adjustments_amount_non_zero_check)

    drop_if_exists constraint(:conduct_marks, :conduct_marks_value_in_range_check)

    drop_if_exists index(:attendance_entries, [:workspace_id, :date])

    drop_if_exists index(:attendance_entries, [:enrollment_id, :date])

    drop_if_exists index(:academic_years, [:workspace_id],
                     name: "academic_years_one_active_per_workspace"
                   )

    drop_if_exists constraint(:academic_years, :academic_years_dates_ordered_check)
  end
end
