defmodule TeacherAssistant.Repo.Migrations.AddPlanCombinedCourse do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:progression_plans) do
      add :combined_course_id,
          references(:combined_courses,
            column: :id,
            name: "progression_plans_combined_course_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      modify :teaching_context_id, :uuid, null: true
    end
  end

  def down do
    drop constraint(:progression_plans, "progression_plans_combined_course_id_fkey")

    alter table(:progression_plans) do
      modify :teaching_context_id, :uuid, null: false
      remove :combined_course_id
    end
  end
end
