defmodule TeacherAssistant.Repo.Migrations.GateIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:attendance_entries, [:enrollment_id])

    create index(:attendance_entries, [:period_id])

    create index(:marks, [:student_id])

    create index(:marks, [:assessment_id])

    create index(:payments, [:enrollment_id])

    create index(:school_memberships, [:user_id])
  end

  def down do
    drop_if_exists index(:school_memberships, [:user_id])

    drop_if_exists index(:payments, [:enrollment_id])

    drop_if_exists index(:marks, [:assessment_id])

    drop_if_exists index(:marks, [:student_id])

    drop_if_exists index(:attendance_entries, [:period_id])

    drop_if_exists index(:attendance_entries, [:enrollment_id])
  end
end
