defmodule TeacherAssistant.Repo.Migrations.AddConductMark do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:conduct_marks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :value, :decimal, null: false
      add :recorded_by_user_id, :uuid
      add :workspace_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :enrollment_id,
          references(:enrollments,
            column: :id,
            name: "conduct_marks_enrollment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :sequence_id,
          references(:sequences,
            column: :id,
            name: "conduct_marks_sequence_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:conduct_marks, [:enrollment_id, :sequence_id],
             name: "conduct_marks_unique_conduct_mark_index"
           )
  end

  def down do
    drop constraint(:conduct_marks, "conduct_marks_enrollment_id_fkey")

    drop constraint(:conduct_marks, "conduct_marks_sequence_id_fkey")

    drop_if_exists unique_index(:conduct_marks, [:enrollment_id, :sequence_id],
                     name: "conduct_marks_unique_conduct_mark_index"
                   )

    drop table(:conduct_marks)
  end
end
