defmodule TeacherAssistant.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:teaching_contexts) do
      add :subject_id,
          references(:subjects,
            column: :id,
            with: [workspace_id: :workspace_id],
            match: :full,
            name: "teaching_contexts_subject_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      modify :coefficient, :decimal, null: true, default: nil
    end

    create index(:teaching_contexts, [:workspace_id, :subject_id])
  end

  def down do
    drop_if_exists index(:teaching_contexts, [:workspace_id, :subject_id])

    drop constraint(:teaching_contexts, "teaching_contexts_subject_id_fkey")

    alter table(:teaching_contexts) do
      modify :coefficient, :decimal, null: false, default: "1"
      remove :subject_id
    end
  end
end
