defmodule TeacherAssistant.Repo.Migrations.EnrollmentTenancy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:attendance_entries, "attendance_entries_enrollment_id_fkey")

    alter table(:attendance_entries) do
      modify :enrollment_id,
             references(:enrollments,
               column: :id,
               name: "attendance_entries_enrollment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop_if_exists unique_index(:class_groups, [:workspace_id, :academic_year_id, :label],
                     name: "class_groups_unique_class_group_index"
                   )

    create unique_index(:class_groups, [:workspace_id, :academic_year_id, :label],
             name: "class_groups_unique_class_group_index"
           )

    drop_if_exists index(:class_groups, [:workspace_id])

    create index(:class_groups, [:workspace_id])

    drop_if_exists index(:class_groups, [:academic_year_id])

    create index(:class_groups, [:workspace_id, :academic_year_id])

    drop_if_exists index(:class_groups, [:form_master_user_id])

    create index(:class_groups, [:workspace_id, :form_master_user_id])

    drop constraint(:conduct_marks, "conduct_marks_enrollment_id_fkey")

    alter table(:conduct_marks) do
      modify :enrollment_id,
             references(:enrollments,
               column: :id,
               name: "conduct_marks_enrollment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop_if_exists unique_index(:enrollments, [:student_id, :academic_year_id],
                     name: "enrollments_unique_enrollment_per_year_index"
                   )

    drop constraint(:enrollments, "enrollments_student_id_fkey")

    create unique_index(:enrollments, [:workspace_id, :student_id, :academic_year_id],
             name: "enrollments_unique_enrollment_per_year_index"
           )

    alter table(:enrollments) do
      modify :student_id,
             references(:students,
               column: :id,
               name: "enrollments_student_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:enrollments, "enrollments_class_group_id_fkey")

    alter table(:enrollments) do
      modify :class_group_id,
             references(:class_groups,
               column: :id,
               name: "enrollments_class_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:enrollments, [:student_id])

    create index(:enrollments, [:workspace_id, :student_id])

    drop_if_exists index(:enrollments, [:class_group_id])

    create index(:enrollments, [:workspace_id, :class_group_id])

    drop_if_exists index(:enrollments, [:academic_year_id])

    create index(:enrollments, [:workspace_id, :academic_year_id])

    drop_if_exists index(:enrollments, [:workspace_id])

    create index(:enrollments, [:workspace_id])

    drop constraint(:fee_adjustments, "fee_adjustments_enrollment_id_fkey")

    alter table(:fee_adjustments) do
      modify :enrollment_id,
             references(:enrollments,
               column: :id,
               name: "fee_adjustments_enrollment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:fee_tranches, "fee_tranches_class_group_id_fkey")

    alter table(:fee_tranches) do
      modify :class_group_id,
             references(:class_groups,
               column: :id,
               name: "fee_tranches_class_group_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:marks, "marks_student_id_fkey")

    alter table(:marks) do
      modify :student_id,
             references(:students,
               column: :id,
               name: "marks_student_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:payments, "payments_enrollment_id_fkey")

    alter table(:payments) do
      modify :enrollment_id,
             references(:enrollments,
               column: :id,
               name: "payments_enrollment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:sanction_entries, "sanction_entries_enrollment_id_fkey")

    alter table(:sanction_entries) do
      modify :enrollment_id,
             references(:enrollments,
               column: :id,
               name: "sanction_entries_enrollment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop_if_exists index(:students, [:workspace_id])

    create index(:students, [:workspace_id])

    drop_if_exists index(:students, [:workspace_id, :matricule],
                     name: "students_unique_matricule_index"
                   )

    create index(:students, [:workspace_id, :matricule],
             name: "students_unique_matricule_index",
             unique: true,
             where: "matricule IS NOT NULL"
           )

    drop constraint(:teaching_contexts, "teaching_contexts_class_group_id_fkey")

    alter table(:teaching_contexts) do
      modify :class_group_id,
             references(:class_groups,
               column: :id,
               name: "teaching_contexts_class_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:timetable_slots, "timetable_slots_class_group_id_fkey")

    alter table(:timetable_slots) do
      modify :class_group_id,
             references(:class_groups,
               column: :id,
               name: "timetable_slots_class_group_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:timetable_slots, "timetable_slots_class_group_id_fkey")

    alter table(:timetable_slots) do
      modify :class_group_id,
             references(:class_groups,
               column: :id,
               name: "timetable_slots_class_group_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:teaching_contexts, "teaching_contexts_class_group_id_fkey")

    alter table(:teaching_contexts) do
      modify :class_group_id,
             references(:class_groups,
               column: :id,
               name: "teaching_contexts_class_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:students, [:workspace_id, :matricule],
                     name: "students_unique_matricule_index"
                   )

    create index(:students, [:workspace_id, :matricule],
             name: "students_unique_matricule_index",
             unique: true,
             where: "matricule IS NOT NULL"
           )

    drop_if_exists index(:students, [:workspace_id])

    create index(:students, [:workspace_id])

    drop constraint(:sanction_entries, "sanction_entries_enrollment_id_fkey")

    alter table(:sanction_entries) do
      modify :enrollment_id,
             references(:enrollments,
               column: :id,
               name: "sanction_entries_enrollment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:payments, "payments_enrollment_id_fkey")

    alter table(:payments) do
      modify :enrollment_id,
             references(:enrollments,
               column: :id,
               name: "payments_enrollment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:marks, "marks_student_id_fkey")

    alter table(:marks) do
      modify :student_id,
             references(:students,
               column: :id,
               name: "marks_student_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:fee_tranches, "fee_tranches_class_group_id_fkey")

    alter table(:fee_tranches) do
      modify :class_group_id,
             references(:class_groups,
               column: :id,
               name: "fee_tranches_class_group_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:fee_adjustments, "fee_adjustments_enrollment_id_fkey")

    alter table(:fee_adjustments) do
      modify :enrollment_id,
             references(:enrollments,
               column: :id,
               name: "fee_adjustments_enrollment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop_if_exists index(:enrollments, [:workspace_id])

    create index(:enrollments, [:workspace_id])

    drop_if_exists index(:enrollments, [:workspace_id, :academic_year_id])

    create index(:enrollments, [:academic_year_id])

    drop_if_exists index(:enrollments, [:workspace_id, :class_group_id])

    create index(:enrollments, [:class_group_id])

    drop_if_exists index(:enrollments, [:workspace_id, :student_id])

    create index(:enrollments, [:student_id])

    drop constraint(:enrollments, "enrollments_class_group_id_fkey")

    drop constraint(:enrollments, "enrollments_student_id_fkey")

    alter table(:enrollments) do
      modify :class_group_id,
             references(:class_groups,
               column: :id,
               name: "enrollments_class_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:enrollments) do
      modify :student_id,
             references(:students,
               column: :id,
               name: "enrollments_student_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop_if_exists unique_index(:enrollments, [:workspace_id, :student_id, :academic_year_id],
                     name: "enrollments_unique_enrollment_per_year_index"
                   )

    create unique_index(:enrollments, [:student_id, :academic_year_id],
             name: "enrollments_unique_enrollment_per_year_index"
           )

    drop constraint(:conduct_marks, "conduct_marks_enrollment_id_fkey")

    alter table(:conduct_marks) do
      modify :enrollment_id,
             references(:enrollments,
               column: :id,
               name: "conduct_marks_enrollment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop_if_exists index(:class_groups, [:workspace_id, :form_master_user_id])

    create index(:class_groups, [:form_master_user_id])

    drop_if_exists index(:class_groups, [:workspace_id, :academic_year_id])

    create index(:class_groups, [:academic_year_id])

    drop_if_exists index(:class_groups, [:workspace_id])

    create index(:class_groups, [:workspace_id])

    drop_if_exists unique_index(:class_groups, [:workspace_id, :academic_year_id, :label],
                     name: "class_groups_unique_class_group_index"
                   )

    create unique_index(:class_groups, [:workspace_id, :academic_year_id, :label],
             name: "class_groups_unique_class_group_index"
           )

    drop constraint(:attendance_entries, "attendance_entries_enrollment_id_fkey")

    alter table(:attendance_entries) do
      modify :enrollment_id,
             references(:enrollments,
               column: :id,
               name: "attendance_entries_enrollment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end
end
