defmodule TeacherAssistant.Repo.Migrations.CoefficientGrid do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:school_profiles) do
      add :class_coefficients_allowed?, :boolean, null: false, default: true
      add :bulletin_group_subtotals?, :boolean, null: false, default: false
    end

    create table(:subject_coefficients, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :subsystem, :text, null: false
      add :level, :text, null: false
      add :serie, :text
      add :coefficient, :decimal, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :subject_id, :uuid, null: false
    end

    create unique_index(:subject_coefficients, [:subject_id, :subsystem, :level, :serie],
             name: "subject_coefficients_unique_cell_index",
             nulls_distinct: false
           )

    alter table(:subject_coefficients) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "subject_coefficients_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    alter table(:subjects) do
      add :bulletin_group, :text, null: false, default: "g3_autres"
      remove :category
    end

    create index(:subjects, [:workspace_id, :id], unique: true)

    alter table(:subject_coefficients) do
      modify :subject_id,
             references(:subjects,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "subject_coefficients_subject_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:subject_coefficients, [:workspace_id, :subject_id])

    create index(:subject_coefficients, [:workspace_id])

    create constraint(:subject_coefficients, :subject_coefficients_positive_check,
             check: """
               coefficient > 0
             """
           )

    alter table(:teaching_contexts) do
      add :subject_id,
          references(:subjects,
            column: :id,
            with: [workspace_id: :workspace_id],
            match: :full,
            name: "teaching_contexts_subject_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      modify :coefficient, :decimal, null: true, default: nil
    end

    create index(:teaching_contexts, [:workspace_id, :subject_id])
  end

  def down do
    drop_if_exists index(:teaching_contexts, [:workspace_id, :subject_id])

    drop constraint(:teaching_contexts, "teaching_contexts_subject_id_fkey")

    alter table(:teaching_contexts) do
      modify :coefficient, :decimal, null: false, default: "1"
      remove :subject_id
    end

    drop_if_exists constraint(:subject_coefficients, :subject_coefficients_positive_check)

    drop_if_exists index(:subject_coefficients, [:workspace_id])

    drop_if_exists index(:subject_coefficients, [:workspace_id, :subject_id])

    drop constraint(:subject_coefficients, "subject_coefficients_workspace_id_fkey")

    drop constraint(:subject_coefficients, "subject_coefficients_subject_id_fkey")

    alter table(:subject_coefficients) do
      modify :subject_id, :uuid
    end

    drop_if_exists index(:subjects, [:workspace_id, :id])

    alter table(:subjects) do
      add :category, :text, null: false, default: "general"
      remove :bulletin_group
    end

    alter table(:subject_coefficients) do
      remove :workspace_id
    end

    drop_if_exists unique_index(:subject_coefficients, [:subject_id, :subsystem, :level, :serie],
                     name: "subject_coefficients_unique_cell_index"
                   )

    drop table(:subject_coefficients)

    alter table(:school_profiles) do
      remove :bulletin_group_subtotals?
      remove :class_coefficients_allowed?
    end
  end
end
