defmodule TeacherAssistant.Repo.Migrations.AddSubjects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:subjects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :code, :text
      add :default_coefficient, :decimal, null: false, default: "1"
      add :category, :text, null: false, default: "general"
      add :position, :bigint, null: false, default: 0
      add :active?, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "subjects_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:subjects, [:workspace_id, :name],
             name: "subjects_unique_subject_name_index"
           )
  end

  def down do
    drop constraint(:subjects, "subjects_workspace_id_fkey")

    drop_if_exists unique_index(:subjects, [:workspace_id, :name],
                     name: "subjects_unique_subject_name_index"
                   )

    drop table(:subjects)
  end
end
