defmodule TeacherAssistant.Repo.Migrations.AddSchoolMembershipAndInvitation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:school_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :roles, {:array, :text}, null: false
      add :status, :text
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "school_memberships_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "school_memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:school_memberships, [:workspace_id, :user_id],
             name: "school_memberships_unique_member_index"
           )

    create table(:school_invitations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :email, :citext, null: false
      add :roles, {:array, :text}, null: false
      add :status, :text, null: false, default: "pending"
      add :token, :text, null: false
      add :expires_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "school_invitations_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :invited_by_user_id,
          references(:users,
            column: :id,
            name: "school_invitations_invited_by_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:school_invitations, [:token],
             name: "school_invitations_unique_token_index"
           )
  end

  def down do
    drop constraint(:school_invitations, "school_invitations_workspace_id_fkey")

    drop constraint(:school_invitations, "school_invitations_invited_by_user_id_fkey")

    drop_if_exists unique_index(:school_invitations, [:token],
                     name: "school_invitations_unique_token_index"
                   )

    drop table(:school_invitations)

    drop constraint(:school_memberships, "school_memberships_workspace_id_fkey")

    drop constraint(:school_memberships, "school_memberships_user_id_fkey")

    drop_if_exists unique_index(:school_memberships, [:workspace_id, :user_id],
                     name: "school_memberships_unique_member_index"
                   )

    drop table(:school_memberships)
  end
end
