defmodule TeacherAssistant.Repo.Migrations.P22TeachingAssignments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:teaching_contexts) do
      modify :subsystem, :text, default: "francophone"

      add :teacher_user_id,
          references(:users,
            column: :id,
            name: "teaching_contexts_teacher_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(
             :teaching_contexts,
             [:workspace_id, :academic_year_id, :class_group_id, :subject],
             name: "teaching_contexts_unique_school_assignment",
             unique: true,
             where: "teacher_user_id IS NOT NULL"
           )

    create index(:teaching_contexts, [:workspace_id, :academic_year_id, :subject, :level, :serie],
             name: "teaching_contexts_unique_personal_context",
             unique: true,
             where: "teacher_user_id IS NULL",
             nulls_distinct: false
           )

    drop_if_exists unique_index(
                     :teaching_contexts,
                     [:workspace_id, :academic_year_id, :subject, :level, :serie],
                     name: "teaching_contexts_unique_context_index"
                   )
  end

  def down do
    create unique_index(
             :teaching_contexts,
             [:workspace_id, :academic_year_id, :subject, :level, :serie],
             name: "teaching_contexts_unique_context_index"
           )

    drop constraint(:teaching_contexts, "teaching_contexts_teacher_user_id_fkey")

    drop_if_exists index(
                     :teaching_contexts,
                     [:workspace_id, :academic_year_id, :subject, :level, :serie],
                     name: "teaching_contexts_unique_personal_context"
                   )

    drop_if_exists index(
                     :teaching_contexts,
                     [:workspace_id, :academic_year_id, :class_group_id, :subject],
                     name: "teaching_contexts_unique_school_assignment"
                   )

    alter table(:teaching_contexts) do
      remove :teacher_user_id
      modify :subsystem, :text, default: nil
    end
  end
end
