defmodule TeacherAssistant.Repo.Migrations.AddAttendanceEntry do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:attendance_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :date, :date, null: false
      add :status, :text, null: false
      add :justified, :boolean, null: false, default: false
      add :justification_note, :text
      add :recorded_by_user_id, :uuid
      add :workspace_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :enrollment_id,
          references(:enrollments,
            column: :id,
            name: "attendance_entries_enrollment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :period_id,
          references(:periods,
            column: :id,
            name: "attendance_entries_period_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :teaching_context_id,
          references(:teaching_contexts,
            column: :id,
            name: "attendance_entries_teaching_context_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:attendance_entries, [:enrollment_id, :date, :period_id],
             name: "attendance_entries_unique_mark_index"
           )
  end

  def down do
    drop constraint(:attendance_entries, "attendance_entries_enrollment_id_fkey")

    drop constraint(:attendance_entries, "attendance_entries_period_id_fkey")

    drop constraint(:attendance_entries, "attendance_entries_teaching_context_id_fkey")

    drop_if_exists unique_index(:attendance_entries, [:enrollment_id, :date, :period_id],
                     name: "attendance_entries_unique_mark_index"
                   )

    drop table(:attendance_entries)
  end
end
