defmodule TeacherAssistant.Repo.Migrations.P27TimetableSlot do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:timetable_slots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :day, :text, null: false
      add :workspace_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :class_group_id,
          references(:class_groups,
            column: :id,
            name: "timetable_slots_class_group_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :teaching_context_id,
          references(:teaching_contexts,
            column: :id,
            name: "timetable_slots_teaching_context_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :period_id,
          references(:periods,
            column: :id,
            name: "timetable_slots_period_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:timetable_slots, [:class_group_id, :day, :period_id],
             name: "timetable_slots_unique_cell_index"
           )
  end

  def down do
    drop constraint(:timetable_slots, "timetable_slots_class_group_id_fkey")

    drop constraint(:timetable_slots, "timetable_slots_teaching_context_id_fkey")

    drop constraint(:timetable_slots, "timetable_slots_period_id_fkey")

    drop_if_exists unique_index(:timetable_slots, [:class_group_id, :day, :period_id],
                     name: "timetable_slots_unique_cell_index"
                   )

    drop table(:timetable_slots)
  end
end
