defmodule TeacherAssistant.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:assessment_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :default_weight, :decimal, null: false
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "assessment_types_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:assessment_types, [:workspace_id, :name],
             name: "assessment_types_unique_type_name_index"
           )

    create index(:assessment_types, [:workspace_id])

    create constraint(:assessment_types, :assessment_types_weight_positive_check,
             check: """
               default_weight > 0
             """
           )

    create index(:assessment_types, [:workspace_id, :id], unique: true)

    alter table(:assessments) do
      add :assessment_type_id,
          references(:assessment_types,
            column: :id,
            with: [workspace_id: :workspace_id],
            match: :simple,
            name: "assessments_assessment_type_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:assessments, [:workspace_id, :assessment_type_id])
  end

  def down do
    drop_if_exists index(:assessments, [:workspace_id, :assessment_type_id])

    drop constraint(:assessments, "assessments_assessment_type_id_fkey")

    alter table(:assessments) do
      remove :assessment_type_id
    end

    drop_if_exists index(:assessment_types, [:workspace_id, :id])

    drop_if_exists constraint(:assessment_types, :assessment_types_weight_positive_check)

    drop_if_exists index(:assessment_types, [:workspace_id])

    drop constraint(:assessment_types, "assessment_types_workspace_id_fkey")

    drop_if_exists unique_index(:assessment_types, [:workspace_id, :name],
                     name: "assessment_types_unique_type_name_index"
                   )

    drop table(:assessment_types)
  end
end
