defmodule TeacherAssistant.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:subjects) do
      add :bulletin_group, :text, null: false, default: "g3_autres"
      remove :category
    end
  end

  def down do
    alter table(:subjects) do
      add :category, :text, null: false, default: "general"
      remove :bulletin_group
    end
  end
end
