defmodule TeacherAssistant.Repo.Migrations.AddFeeTranche do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:fee_tranches, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :label, :text, null: false
      add :amount, :bigint, null: false
      add :due_date, :date, null: false
      add :position, :bigint, null: false
      add :workspace_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :class_group_id,
          references(:class_groups,
            column: :id,
            name: "fee_tranches_class_group_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end
  end

  def down do
    drop constraint(:fee_tranches, "fee_tranches_class_group_id_fkey")

    drop table(:fee_tranches)
  end
end
