defmodule TeacherAssistant.Repo.Migrations.AddContextCombinedCourse do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:teaching_contexts) do
      add :combined_course_id,
          references(:combined_courses,
            column: :id,
            name: "teaching_contexts_combined_course_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:teaching_contexts, "teaching_contexts_combined_course_id_fkey")

    alter table(:teaching_contexts) do
      remove :combined_course_id
    end
  end
end
