defmodule TeacherAssistant.Repo.Migrations.MigrateResources8 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:teaching_log_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :date, :date, null: false
      add :content_taught, :text, null: false
      add :hours, :decimal, default: "1"
      add :status, :text, null: false, default: "done"
      add :homework, :text
      add :note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :personal_workspace_id,
          references(:personal_workspaces,
            column: :id,
            name: "teaching_log_entries_personal_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :progression_entry_id,
          references(:progression_entries,
            column: :id,
            name: "teaching_log_entries_progression_entry_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:teaching_log_entries, "teaching_log_entries_personal_workspace_id_fkey")

    drop constraint(:teaching_log_entries, "teaching_log_entries_progression_entry_id_fkey")

    drop table(:teaching_log_entries)
  end
end
