defmodule TeacherAssistant.Repo.Migrations.CurriculumTenancy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:assessments, "assessments_teaching_context_id_fkey")

    alter table(:assessments) do
      modify :teaching_context_id,
             references(:teaching_contexts,
               column: :id,
               name: "assessments_teaching_context_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:attendance_entries, "attendance_entries_teaching_context_id_fkey")

    alter table(:attendance_entries) do
      modify :teaching_context_id,
             references(:teaching_contexts,
               column: :id,
               name: "attendance_entries_teaching_context_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:combined_courses, [:workspace_id])

    create index(:combined_courses, [:workspace_id])

    drop_if_exists index(:combined_courses, [:academic_year_id])

    create index(:combined_courses, [:workspace_id, :academic_year_id])

    drop_if_exists index(:combined_courses, [:teacher_user_id])

    create index(:combined_courses, [:workspace_id, :teacher_user_id])

    drop_if_exists unique_index(:lesson_plans, [:progression_entry_id],
                     name: "lesson_plans_unique_entry_index"
                   )

    drop constraint(:lesson_plans, "lesson_plans_progression_entry_id_fkey")

    create unique_index(:lesson_plans, [:workspace_id, :progression_entry_id],
             name: "lesson_plans_unique_entry_index"
           )

    alter table(:lesson_plans) do
      modify :progression_entry_id,
             references(:progression_entries,
               column: :id,
               name: "lesson_plans_progression_entry_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:lesson_plans, [:progression_entry_id])

    create index(:lesson_plans, [:workspace_id, :progression_entry_id])

    drop_if_exists index(:lesson_plans, [:workspace_id])

    create index(:lesson_plans, [:workspace_id])

    drop constraint(:lesson_steps, "lesson_steps_lesson_plan_id_fkey")

    alter table(:lesson_steps) do
      modify :lesson_plan_id,
             references(:lesson_plans,
               column: :id,
               name: "lesson_steps_lesson_plan_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:lesson_steps, [:lesson_plan_id])

    create index(:lesson_steps, [:workspace_id, :lesson_plan_id])

    drop_if_exists index(:lesson_steps, [:workspace_id])

    create index(:lesson_steps, [:workspace_id])

    drop constraint(:progression_entries, "progression_entries_progression_plan_id_fkey")

    alter table(:progression_entries) do
      modify :progression_plan_id,
             references(:progression_plans,
               column: :id,
               name: "progression_entries_progression_plan_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:progression_entries, "progression_entries_progression_module_id_fkey")

    alter table(:progression_entries) do
      modify :progression_module_id,
             references(:progression_modules,
               column: :id,
               name: "progression_entries_progression_module_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:progression_entries, [:progression_plan_id])

    create index(:progression_entries, [:workspace_id, :progression_plan_id])

    drop_if_exists index(:progression_entries, [:sequence_id])

    create index(:progression_entries, [:workspace_id, :sequence_id])

    drop_if_exists index(:progression_entries, [:progression_module_id])

    create index(:progression_entries, [:workspace_id, :progression_module_id])

    drop_if_exists index(:progression_entries, [:workspace_id])

    create index(:progression_entries, [:workspace_id])

    create index(:progression_entries, [:workspace_id, :progression_module_id, :position])

    drop_if_exists index(:progression_entries, [:progression_module_id, :position])

    drop constraint(:progression_modules, "progression_modules_progression_plan_id_fkey")

    alter table(:progression_modules) do
      modify :progression_plan_id,
             references(:progression_plans,
               column: :id,
               name: "progression_modules_progression_plan_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:progression_modules, [:progression_plan_id])

    create index(:progression_modules, [:workspace_id, :progression_plan_id])

    drop_if_exists index(:progression_modules, [:sequence_id])

    create index(:progression_modules, [:workspace_id, :sequence_id])

    drop_if_exists index(:progression_modules, [:workspace_id])

    create index(:progression_modules, [:workspace_id])

    drop constraint(:progression_plans, "progression_plans_teaching_context_id_fkey")

    alter table(:progression_plans) do
      modify :teaching_context_id,
             references(:teaching_contexts,
               column: :id,
               name: "progression_plans_teaching_context_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:progression_plans, "progression_plans_combined_course_id_fkey")

    alter table(:progression_plans) do
      modify :combined_course_id,
             references(:combined_courses,
               column: :id,
               name: "progression_plans_combined_course_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    drop_if_exists index(:progression_plans, [:teaching_context_id])

    create index(:progression_plans, [:workspace_id, :teaching_context_id])

    drop_if_exists index(:progression_plans, [:combined_course_id])

    create index(:progression_plans, [:workspace_id, :combined_course_id])

    drop_if_exists index(:progression_plans, [:academic_year_id])

    create index(:progression_plans, [:workspace_id, :academic_year_id])

    drop_if_exists index(:progression_plans, [:workspace_id])

    create index(:progression_plans, [:workspace_id])

    drop_if_exists unique_index(:subjects, [:workspace_id, :name],
                     name: "subjects_unique_subject_name_index"
                   )

    create unique_index(:subjects, [:workspace_id, :name],
             name: "subjects_unique_subject_name_index"
           )

    drop_if_exists index(:subjects, [:workspace_id])

    create index(:subjects, [:workspace_id])

    drop constraint(:teaching_contexts, "teaching_contexts_combined_course_id_fkey")

    alter table(:teaching_contexts) do
      modify :combined_course_id,
             references(:combined_courses,
               column: :id,
               name: "teaching_contexts_combined_course_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    drop_if_exists index(:teaching_contexts, [:workspace_id])

    create index(:teaching_contexts, [:workspace_id])

    drop_if_exists index(:teaching_contexts, [:academic_year_id])

    create index(:teaching_contexts, [:workspace_id, :academic_year_id])

    drop_if_exists index(:teaching_contexts, [:class_group_id])

    create index(:teaching_contexts, [:workspace_id, :class_group_id])

    drop_if_exists index(:teaching_contexts, [:teacher_user_id])

    create index(:teaching_contexts, [:workspace_id, :teacher_user_id])

    drop_if_exists index(:teaching_contexts, [:combined_course_id])

    create index(:teaching_contexts, [:workspace_id, :combined_course_id])

    drop_if_exists index(
                     :teaching_contexts,
                     [:workspace_id, :academic_year_id, :class_group_id, :subject],
                     name: "teaching_contexts_unique_school_assignment"
                   )

    create index(
             :teaching_contexts,
             [:workspace_id, :academic_year_id, :class_group_id, :subject],
             name: "teaching_contexts_unique_school_assignment",
             unique: true
           )

    drop constraint(:teaching_log_entries, "teaching_log_entries_progression_entry_id_fkey")

    alter table(:teaching_log_entries) do
      modify :progression_entry_id,
             references(:progression_entries,
               column: :id,
               name: "teaching_log_entries_progression_entry_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:teaching_log_entries, [:workspace_id])

    create index(:teaching_log_entries, [:workspace_id])

    drop_if_exists index(:teaching_log_entries, [:progression_entry_id])

    create index(:teaching_log_entries, [:workspace_id, :progression_entry_id])

    drop constraint(:timetable_slots, "timetable_slots_teaching_context_id_fkey")

    alter table(:timetable_slots) do
      modify :teaching_context_id,
             references(:teaching_contexts,
               column: :id,
               name: "timetable_slots_teaching_context_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:timetable_slots, "timetable_slots_teaching_context_id_fkey")

    alter table(:timetable_slots) do
      modify :teaching_context_id,
             references(:teaching_contexts,
               column: :id,
               name: "timetable_slots_teaching_context_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop_if_exists index(:teaching_log_entries, [:workspace_id, :progression_entry_id])

    create index(:teaching_log_entries, [:progression_entry_id])

    drop_if_exists index(:teaching_log_entries, [:workspace_id])

    create index(:teaching_log_entries, [:workspace_id])

    drop constraint(:teaching_log_entries, "teaching_log_entries_progression_entry_id_fkey")

    alter table(:teaching_log_entries) do
      modify :progression_entry_id,
             references(:progression_entries,
               column: :id,
               name: "teaching_log_entries_progression_entry_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(
                     :teaching_contexts,
                     [:workspace_id, :academic_year_id, :class_group_id, :subject],
                     name: "teaching_contexts_unique_school_assignment"
                   )

    create index(
             :teaching_contexts,
             [:workspace_id, :academic_year_id, :class_group_id, :subject],
             name: "teaching_contexts_unique_school_assignment",
             unique: true
           )

    drop_if_exists index(:teaching_contexts, [:workspace_id, :combined_course_id])

    create index(:teaching_contexts, [:combined_course_id])

    drop_if_exists index(:teaching_contexts, [:workspace_id, :teacher_user_id])

    create index(:teaching_contexts, [:teacher_user_id])

    drop_if_exists index(:teaching_contexts, [:workspace_id, :class_group_id])

    create index(:teaching_contexts, [:class_group_id])

    drop_if_exists index(:teaching_contexts, [:workspace_id, :academic_year_id])

    create index(:teaching_contexts, [:academic_year_id])

    drop_if_exists index(:teaching_contexts, [:workspace_id])

    create index(:teaching_contexts, [:workspace_id])

    drop constraint(:teaching_contexts, "teaching_contexts_combined_course_id_fkey")

    alter table(:teaching_contexts) do
      modify :combined_course_id,
             references(:combined_courses,
               column: :id,
               name: "teaching_contexts_combined_course_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    drop_if_exists index(:subjects, [:workspace_id])

    create index(:subjects, [:workspace_id])

    drop_if_exists unique_index(:subjects, [:workspace_id, :name],
                     name: "subjects_unique_subject_name_index"
                   )

    create unique_index(:subjects, [:workspace_id, :name],
             name: "subjects_unique_subject_name_index"
           )

    drop_if_exists index(:progression_plans, [:workspace_id])

    create index(:progression_plans, [:workspace_id])

    drop_if_exists index(:progression_plans, [:workspace_id, :academic_year_id])

    create index(:progression_plans, [:academic_year_id])

    drop_if_exists index(:progression_plans, [:workspace_id, :combined_course_id])

    create index(:progression_plans, [:combined_course_id])

    drop_if_exists index(:progression_plans, [:workspace_id, :teaching_context_id])

    create index(:progression_plans, [:teaching_context_id])

    drop constraint(:progression_plans, "progression_plans_combined_course_id_fkey")

    drop constraint(:progression_plans, "progression_plans_teaching_context_id_fkey")

    alter table(:progression_plans) do
      modify :combined_course_id,
             references(:combined_courses,
               column: :id,
               name: "progression_plans_combined_course_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:progression_plans) do
      modify :teaching_context_id,
             references(:teaching_contexts,
               column: :id,
               name: "progression_plans_teaching_context_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:progression_modules, [:workspace_id])

    create index(:progression_modules, [:workspace_id])

    drop_if_exists index(:progression_modules, [:workspace_id, :sequence_id])

    create index(:progression_modules, [:sequence_id])

    drop_if_exists index(:progression_modules, [:workspace_id, :progression_plan_id])

    create index(:progression_modules, [:progression_plan_id])

    drop constraint(:progression_modules, "progression_modules_progression_plan_id_fkey")

    alter table(:progression_modules) do
      modify :progression_plan_id,
             references(:progression_plans,
               column: :id,
               name: "progression_modules_progression_plan_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:progression_entries, [:progression_module_id, :position])

    drop_if_exists index(:progression_entries, [:workspace_id, :progression_module_id, :position])

    drop_if_exists index(:progression_entries, [:workspace_id])

    create index(:progression_entries, [:workspace_id])

    drop_if_exists index(:progression_entries, [:workspace_id, :progression_module_id])

    create index(:progression_entries, [:progression_module_id])

    drop_if_exists index(:progression_entries, [:workspace_id, :sequence_id])

    create index(:progression_entries, [:sequence_id])

    drop_if_exists index(:progression_entries, [:workspace_id, :progression_plan_id])

    create index(:progression_entries, [:progression_plan_id])

    drop constraint(:progression_entries, "progression_entries_progression_module_id_fkey")

    drop constraint(:progression_entries, "progression_entries_progression_plan_id_fkey")

    alter table(:progression_entries) do
      modify :progression_module_id,
             references(:progression_modules,
               column: :id,
               name: "progression_entries_progression_module_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:progression_entries) do
      modify :progression_plan_id,
             references(:progression_plans,
               column: :id,
               name: "progression_entries_progression_plan_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:lesson_steps, [:workspace_id])

    create index(:lesson_steps, [:workspace_id])

    drop_if_exists index(:lesson_steps, [:workspace_id, :lesson_plan_id])

    create index(:lesson_steps, [:lesson_plan_id])

    drop constraint(:lesson_steps, "lesson_steps_lesson_plan_id_fkey")

    alter table(:lesson_steps) do
      modify :lesson_plan_id,
             references(:lesson_plans,
               column: :id,
               name: "lesson_steps_lesson_plan_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:lesson_plans, [:workspace_id])

    create index(:lesson_plans, [:workspace_id])

    drop_if_exists index(:lesson_plans, [:workspace_id, :progression_entry_id])

    create index(:lesson_plans, [:progression_entry_id])

    drop constraint(:lesson_plans, "lesson_plans_progression_entry_id_fkey")

    alter table(:lesson_plans) do
      modify :progression_entry_id,
             references(:progression_entries,
               column: :id,
               name: "lesson_plans_progression_entry_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists unique_index(:lesson_plans, [:workspace_id, :progression_entry_id],
                     name: "lesson_plans_unique_entry_index"
                   )

    create unique_index(:lesson_plans, [:progression_entry_id],
             name: "lesson_plans_unique_entry_index"
           )

    drop_if_exists index(:combined_courses, [:workspace_id, :teacher_user_id])

    create index(:combined_courses, [:teacher_user_id])

    drop_if_exists index(:combined_courses, [:workspace_id, :academic_year_id])

    create index(:combined_courses, [:academic_year_id])

    drop_if_exists index(:combined_courses, [:workspace_id])

    create index(:combined_courses, [:workspace_id])

    drop constraint(:attendance_entries, "attendance_entries_teaching_context_id_fkey")

    alter table(:attendance_entries) do
      modify :teaching_context_id,
             references(:teaching_contexts,
               column: :id,
               name: "attendance_entries_teaching_context_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:assessments, "assessments_teaching_context_id_fkey")

    alter table(:assessments) do
      modify :teaching_context_id,
             references(:teaching_contexts,
               column: :id,
               name: "assessments_teaching_context_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
