defmodule TeacherAssistant.Repo.Migrations.AddSanctionEntry do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sanction_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :type, :text, null: false
      add :date, :date, null: false
      add :reason, :text
      add :duration_days, :bigint
      add :issued_by_user_id, :uuid
      add :workspace_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :enrollment_id,
          references(:enrollments,
            column: :id,
            name: "sanction_entries_enrollment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end
  end

  def down do
    drop constraint(:sanction_entries, "sanction_entries_enrollment_id_fkey")

    drop table(:sanction_entries)
  end
end
