defmodule TeacherAssistant.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:subjects) do
      add :optional?, :boolean, null: false, default: false
    end

    create table(:subject_exemptions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :teaching_context_id, :uuid, null: false
      add :student_id, :uuid, null: false
    end

    create unique_index(:subject_exemptions, [:teaching_context_id, :student_id],
             name: "subject_exemptions_unique_exemption_index"
           )

    alter table(:subject_exemptions) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "subject_exemptions_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      modify :teaching_context_id,
             references(:teaching_contexts,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "subject_exemptions_teaching_context_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :student_id,
             references(:students,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "subject_exemptions_student_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:subject_exemptions, [:workspace_id, :teaching_context_id])

    create index(:subject_exemptions, [:workspace_id, :student_id])

    create index(:subject_exemptions, [:workspace_id])
  end

  def down do
    drop_if_exists index(:subject_exemptions, [:workspace_id])

    drop_if_exists index(:subject_exemptions, [:workspace_id, :student_id])

    drop_if_exists index(:subject_exemptions, [:workspace_id, :teaching_context_id])

    drop constraint(:subject_exemptions, "subject_exemptions_workspace_id_fkey")

    drop constraint(:subject_exemptions, "subject_exemptions_student_id_fkey")

    drop constraint(:subject_exemptions, "subject_exemptions_teaching_context_id_fkey")

    alter table(:subject_exemptions) do
      modify :student_id, :uuid
      modify :teaching_context_id, :uuid
      remove :workspace_id
    end

    drop_if_exists unique_index(:subject_exemptions, [:teaching_context_id, :student_id],
                     name: "subject_exemptions_unique_exemption_index"
                   )

    drop table(:subject_exemptions)

    alter table(:subjects) do
      remove :optional?
    end
  end
end
