defmodule TeacherAssistant.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:school_profiles) do
      add :absence_rule, :text, null: false, default: "zero"
      add :default_max_score, :decimal, null: false, default: "20"
    end

    create constraint(:school_profiles, :school_profiles_default_max_positive_check,
             check: """
               default_max_score > 0
             """
           )
  end

  def down do
    drop_if_exists constraint(:school_profiles, :school_profiles_default_max_positive_check)

    alter table(:school_profiles) do
      remove :default_max_score
      remove :absence_rule
    end
  end
end
