defmodule TeacherAssistant.Repo.Migrations.CreateSchoolProfiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:school_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :short_name, :text
      add :school_type, :text, null: false
      add :subsystem, :text, null: false
      add :sector, :text, null: false
      add :region, :text, null: false
      add :department, :text
      add :town, :text, null: false
      add :phone, :text
      add :email, :text
      add :address, :text
      add :head_name, :text
      add :motto, :text
      add :registration_number, :text
      add :logo_path, :text
      add :verification_status, :text, null: false, default: "unverified"
      add :verified_at, :utc_datetime_usec
      add :verified_by_user_id, :uuid
      add :rejection_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "school_profiles_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:school_profiles, [:workspace_id],
             name: "school_profiles_unique_workspace_index"
           )

    alter table(:school_profiles) do
      add :owner_user_id,
          references(:users,
            column: :id,
            name: "school_profiles_owner_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:school_profiles, "school_profiles_owner_user_id_fkey")

    drop constraint(:school_profiles, "school_profiles_workspace_id_fkey")

    alter table(:school_profiles) do
      remove :owner_user_id
    end

    drop_if_exists unique_index(:school_profiles, [:workspace_id],
                     name: "school_profiles_unique_workspace_index"
                   )

    drop table(:school_profiles)
  end
end
