defmodule TeacherAssistant.Repo.Migrations.AddAssessmentsAndContextClassGroup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:teaching_contexts) do
      add :class_group_id,
          references(:class_groups,
            column: :id,
            name: "teaching_contexts_class_group_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:assessments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :label, :text, null: false
      add :weight, :decimal, null: false, default: "1"
      add :max_score, :decimal, null: false, default: "20"
      add :given_on, :date

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :teaching_context_id,
          references(:teaching_contexts,
            column: :id,
            name: "assessments_teaching_context_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :sequence_id,
          references(:sequences,
            column: :id,
            name: "assessments_sequence_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:assessments, "assessments_teaching_context_id_fkey")

    drop constraint(:assessments, "assessments_sequence_id_fkey")

    drop table(:assessments)

    drop constraint(:teaching_contexts, "teaching_contexts_class_group_id_fkey")

    alter table(:teaching_contexts) do
      remove :class_group_id
    end
  end
end
