defmodule TeacherAssistant.Repo.Migrations.AccountsTenancy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:school_invitations, [:token],
                     name: "school_invitations_unique_token_index"
                   )

    create unique_index(:school_invitations, [:token],
             name: "school_invitations_unique_token_index"
           )

    drop_if_exists index(:school_invitations, [:workspace_id])

    create index(:school_invitations, [:workspace_id])

    drop_if_exists index(:school_invitations, [:invited_by_user_id])

    create index(:school_invitations, [:workspace_id, :invited_by_user_id])

    drop_if_exists unique_index(:school_memberships, [:workspace_id, :user_id],
                     name: "school_memberships_unique_member_index"
                   )

    create unique_index(:school_memberships, [:workspace_id, :user_id],
             name: "school_memberships_unique_member_index"
           )

    drop_if_exists index(:school_memberships, [:workspace_id])

    create index(:school_memberships, [:workspace_id])

    drop_if_exists index(:school_memberships, [:user_id])

    create index(:school_memberships, [:workspace_id, :user_id])
  end

  def down do
    drop_if_exists index(:school_memberships, [:workspace_id, :user_id])

    create index(:school_memberships, [:user_id])

    drop_if_exists index(:school_memberships, [:workspace_id])

    create index(:school_memberships, [:workspace_id])

    drop_if_exists unique_index(:school_memberships, [:workspace_id, :user_id],
                     name: "school_memberships_unique_member_index"
                   )

    create unique_index(:school_memberships, [:workspace_id, :user_id],
             name: "school_memberships_unique_member_index"
           )

    drop_if_exists index(:school_invitations, [:workspace_id, :invited_by_user_id])

    create index(:school_invitations, [:invited_by_user_id])

    drop_if_exists index(:school_invitations, [:workspace_id])

    create index(:school_invitations, [:workspace_id])

    drop_if_exists unique_index(:school_invitations, [:token],
                     name: "school_invitations_unique_token_index"
                   )

    create unique_index(:school_invitations, [:token],
             name: "school_invitations_unique_token_index"
           )
  end
end
