defmodule TeacherAssistant.Repo.Migrations.MarksAbsence do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:assessment_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :default_weight, :decimal, null: false
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "assessment_types_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:assessment_types, [:workspace_id, :name],
             name: "assessment_types_unique_type_name_index"
           )

    create index(:assessment_types, [:workspace_id])

    create constraint(:assessment_types, :assessment_types_weight_positive_check,
             check: """
               default_weight > 0
             """
           )

    create index(:assessment_types, [:workspace_id, :id], unique: true)

    alter table(:subjects) do
      add :optional?, :boolean, null: false, default: false
    end

    alter table(:school_profiles) do
      add :absence_rule, :text, null: false, default: "zero"
      add :default_max_score, :decimal, null: false, default: "20"
    end

    create constraint(:school_profiles, :school_profiles_default_max_positive_check,
             check: """
               default_max_score > 0
             """
           )

    alter table(:marks) do
      add :status, :text, null: false, default: "graded"
    end

    create constraint(:marks, :marks_status_score_check,
             check: """
               (status = 'graded') = (score IS NOT NULL)
             """
           )

    alter table(:assessments) do
      add :assessment_type_id,
          references(:assessment_types,
            column: :id,
            with: [workspace_id: :workspace_id],
            match: :simple,
            name: "assessments_assessment_type_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:assessments, [:workspace_id, :assessment_type_id])

    create table(:subject_exemptions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :teaching_context_id, :uuid, null: false
      add :student_id, :uuid, null: false
    end

    create unique_index(:subject_exemptions, [:teaching_context_id, :student_id],
             name: "subject_exemptions_unique_exemption_index"
           )

    alter table(:subject_exemptions) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "subject_exemptions_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      modify :teaching_context_id,
             references(:teaching_contexts,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "subject_exemptions_teaching_context_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :student_id,
             references(:students,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "subject_exemptions_student_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:subject_exemptions, [:workspace_id, :teaching_context_id])

    create index(:subject_exemptions, [:workspace_id, :student_id])

    create index(:subject_exemptions, [:workspace_id])
  end

  def down do
    drop_if_exists index(:subject_exemptions, [:workspace_id])

    drop_if_exists index(:subject_exemptions, [:workspace_id, :student_id])

    drop_if_exists index(:subject_exemptions, [:workspace_id, :teaching_context_id])

    drop constraint(:subject_exemptions, "subject_exemptions_workspace_id_fkey")

    drop constraint(:subject_exemptions, "subject_exemptions_student_id_fkey")

    drop constraint(:subject_exemptions, "subject_exemptions_teaching_context_id_fkey")

    alter table(:subject_exemptions) do
      modify :student_id, :uuid
      modify :teaching_context_id, :uuid
      remove :workspace_id
    end

    drop_if_exists unique_index(:subject_exemptions, [:teaching_context_id, :student_id],
                     name: "subject_exemptions_unique_exemption_index"
                   )

    drop table(:subject_exemptions)

    drop_if_exists index(:assessments, [:workspace_id, :assessment_type_id])

    drop constraint(:assessments, "assessments_assessment_type_id_fkey")

    alter table(:assessments) do
      remove :assessment_type_id
    end

    drop_if_exists constraint(:marks, :marks_status_score_check)

    alter table(:marks) do
      remove :status
    end

    drop_if_exists constraint(:school_profiles, :school_profiles_default_max_positive_check)

    alter table(:school_profiles) do
      remove :default_max_score
      remove :absence_rule
    end

    alter table(:subjects) do
      remove :optional?
    end

    drop_if_exists index(:assessment_types, [:workspace_id, :id])

    drop_if_exists constraint(:assessment_types, :assessment_types_weight_positive_check)

    drop_if_exists index(:assessment_types, [:workspace_id])

    drop constraint(:assessment_types, "assessment_types_workspace_id_fkey")

    drop_if_exists unique_index(:assessment_types, [:workspace_id, :name],
                     name: "assessment_types_unique_type_name_index"
                   )

    drop table(:assessment_types)
  end
end
