defmodule TeacherAssistant.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:personal_workspaces, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_user_id,
          references(:users,
            column: :id,
            name: "personal_workspaces_owner_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:personal_workspaces, [:owner_user_id],
             name: "personal_workspaces_unique_owner_user_index"
           )
  end

  def down do
    drop constraint(:personal_workspaces, "personal_workspaces_owner_user_id_fkey")

    drop_if_exists unique_index(:personal_workspaces, [:owner_user_id],
                     name: "personal_workspaces_unique_owner_user_index"
                   )

    drop table(:personal_workspaces)
  end
end
