defmodule TeacherAssistant.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:schools) do
      add :workspace_type, :text, null: false, default: "school"

      add :owner_user_id,
          references(:users,
            column: :id,
            name: "schools_owner_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:school_invitations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :email, :citext, null: false
      add :role, :text, null: false, default: "teacher"
      add :token, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :accepted_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :school_id,
          references(:schools,
            column: :id,
            name: "school_invitations_school_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :invited_by_user_id,
          references(:users,
            column: :id,
            name: "school_invitations_invited_by_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :accepted_by_user_id,
          references(:users,
            column: :id,
            name: "school_invitations_accepted_by_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:school_invitations, [:token],
             name: "school_invitations_unique_token_index"
           )
  end

  def down do
    drop constraint(:school_invitations, "school_invitations_school_id_fkey")

    drop constraint(:school_invitations, "school_invitations_invited_by_user_id_fkey")

    drop constraint(:school_invitations, "school_invitations_accepted_by_user_id_fkey")

    drop_if_exists unique_index(:school_invitations, [:token],
                     name: "school_invitations_unique_token_index"
                   )

    drop table(:school_invitations)

    drop constraint(:schools, "schools_owner_user_id_fkey")

    alter table(:schools) do
      remove :owner_user_id
      remove :workspace_type
    end
  end
end
