defmodule TeacherAssistant.Repo.Migrations.FoundationRebuild do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    CREATE OR REPLACE FUNCTION uuid_generate_v7()
    RETURNS UUID
    AS $$
    DECLARE
      timestamp    TIMESTAMPTZ;
      microseconds INT;
    BEGIN
      timestamp    = clock_timestamp();
      microseconds = (cast(extract(microseconds FROM timestamp)::INT - (floor(extract(milliseconds FROM timestamp))::INT * 1000) AS DOUBLE PRECISION) * 4.096)::INT;

      RETURN encode(
        set_byte(
          set_byte(
            overlay(uuid_send(gen_random_uuid()) placing substring(int8send(floor(extract(epoch FROM timestamp) * 1000)::BIGINT) FROM 3) FROM 1 FOR 6
          ),
          6, (b'0111' || (microseconds >> 8)::bit(4))::bit(8)::int
        ),
        7, microseconds::bit(8)::int
      ),
      'hex')::UUID;
    END
    $$
    LANGUAGE PLPGSQL
    SET search_path = ''
    VOLATILE;
    """)

    create table(:users_schools, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :role, :text, null: false, default: "teacher"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :school_id, :uuid, null: false
      add :user_id, :uuid, null: false
    end

    create unique_index(:users_schools, [:school_id, :user_id],
             name: "users_schools_unique_user_school_index"
           )

    execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS role text DEFAULT 'teacher'")

    create table(:terms, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :start_date, :date
      add :end_date, :date
      add :position, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :school_id, :uuid
      add :academic_year_id, :uuid, null: false
    end

    create unique_index(:terms, [:school_id, :name, :academic_year_id],
             name: "terms_unique_name_index"
           )

    create table(:teaching_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :taught_on, :date, null: false
      add :taught_hours, :decimal, null: false, default: "0"
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :school_id, :uuid
      add :progression_entry_id, :uuid, null: false
    end

    create table(:subjects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :default_coefficient, :bigint, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :school_id, :uuid
    end

    create unique_index(:subjects, [:school_id, :name], name: "subjects_unique_name_index")

    create table(:students, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :first_name, :citext, null: false
      add :last_name, :citext, null: false
      add :matricule, :text
      add :place_of_birth, :text
      add :date_of_birth, :date
      add :gender, :text, null: false, default: "male"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :school_id, :uuid
    end

    create unique_index(:students, [:school_id, :first_name, :last_name, :date_of_birth],
             name: "students_unique_name_and_date_of_birth_index"
           )

    create table(:sequences_subjects_objectives, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :objective, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :school_id, :uuid
      add :sequence_id, :uuid, null: false
      add :level_option_subject_id, :uuid, null: false
    end

    create unique_index(
             :sequences_subjects_objectives,
             [:school_id, :sequence_id, :level_option_subject_id],
             name: "sequences_subjects_objectives_unique_sequence_subject_index"
           )

    create table(:sequences, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :start_date, :date
      add :end_date, :date
      add :position, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :school_id, :uuid
      add :term_id, :uuid, null: false
    end

    create table(:schools, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:users_schools) do
      modify :school_id,
             references(:schools,
               column: :id,
               name: "users_schools_school_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "users_schools_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:terms) do
      modify :school_id,
             references(:schools,
               column: :id,
               name: "terms_school_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:teaching_logs) do
      modify :school_id,
             references(:schools,
               column: :id,
               name: "teaching_logs_school_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:subjects) do
      modify :school_id,
             references(:schools,
               column: :id,
               name: "subjects_school_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:students) do
      modify :school_id,
             references(:schools,
               column: :id,
               name: "students_school_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:sequences_subjects_objectives) do
      modify :school_id,
             references(:schools,
               column: :id,
               name: "sequences_subjects_objectives_school_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :sequence_id,
             references(:sequences,
               column: :id,
               name: "sequences_subjects_objectives_sequence_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:sequences) do
      modify :school_id,
             references(:schools,
               column: :id,
               name: "sequences_school_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :term_id,
             references(:terms,
               column: :id,
               name: "sequences_term_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:schools) do
      add :name, :text, null: false
      add :abbreviation, :text
      add :type, :text
      add :sub_system, :text
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:schools, [:name], name: "schools_unique_name_index")

    create table(:school_year_subject_teachers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :school_id,
          references(:schools,
            column: :id,
            name: "school_year_subject_teachers_school_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :classroom_id, :uuid, null: false
      add :level_option_subject_id, :uuid, null: false
      add :teacher_id, :uuid, null: false
    end

    create unique_index(
             :school_year_subject_teachers,
             [:school_id, :classroom_id, :level_option_subject_id, :teacher_id],
             name: "school_year_subject_teachers_unique_assignment_index"
           )

    create table(:progression_plans, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :weekly_hours, :decimal, null: false, default: "0"
      add :annual_hours, :decimal, null: false, default: "0"
      add :status, :text, null: false, default: "draft"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec

      add :school_id,
          references(:schools,
            column: :id,
            name: "progression_plans_school_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :academic_year_id, :uuid, null: false
      add :classroom_id, :uuid, null: false
      add :level_option_subject_id, :uuid, null: false
      add :teacher_id, :uuid, null: false
    end

    create unique_index(
             :progression_plans,
             [
               :school_id,
               :academic_year_id,
               :classroom_id,
               :level_option_subject_id,
               :teacher_id
             ],
             name: "progression_plans_unique_teacher_progression_plan_index"
           )

    create table(:progression_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:teaching_logs) do
      modify :progression_entry_id,
             references(:progression_entries,
               column: :id,
               name: "teaching_logs_progression_entry_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:progression_entries) do
      add :week_number, :bigint
      add :start_date, :date
      add :end_date, :date
      add :title, :text, null: false
      add :planned_content, :text
      add :planned_hours, :decimal, null: false, default: "0"
      add :entry_type, :text, null: false, default: "lesson"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec

      add :school_id,
          references(:schools,
            column: :id,
            name: "progression_entries_school_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :progression_plan_id,
          references(:progression_plans,
            column: :id,
            name: "progression_entries_progression_plan_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :term_id,
          references(:terms,
            column: :id,
            name: "progression_entries_term_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :sequence_id,
          references(:sequences,
            column: :id,
            name: "progression_entries_sequence_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:options, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :citext, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec

      add :school_id,
          references(:schools,
            column: :id,
            name: "options_school_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:options, [:school_id, :name], name: "options_unique_name_index")

    create table(:marks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :score, :decimal, null: false
      add :comment, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec

      add :school_id,
          references(:schools,
            column: :id,
            name: "marks_school_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :student_id,
          references(:students,
            column: :id,
            name: "marks_student_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :classroom_id, :uuid, null: false
      add :sequence_id, :uuid, null: false
      add :level_option_subject_id, :uuid, null: false
    end

    create unique_index(:marks, [:school_id, :student_id, :level_option_subject_id, :sequence_id],
             name: "marks_unique_mark_index"
           )

    create table(:levels_options_subjects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:sequences_subjects_objectives) do
      modify :level_option_subject_id,
             references(:levels_options_subjects,
               column: :id,
               name: "sequences_subjects_objectives_level_option_subject_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:levels_options_subjects) do
      add :coefficient, :bigint, null: false
      add :level_option_id, :uuid, null: false
      add :subject_id, :uuid, null: false
    end

    create unique_index(:levels_options_subjects, [:level_option_id, :subject_id],
             name: "levels_options_subjects_name_index"
           )

    create table(:levels_options, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:levels_options_subjects) do
      modify :level_option_id,
             references(:levels_options,
               column: :id,
               name: "levels_options_subjects_level_option_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :subject_id,
             references(:subjects,
               column: :id,
               name: "levels_options_subjects_subject_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:levels_options) do
      add :school_id,
          references(:schools,
            column: :id,
            name: "levels_options_school_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :option_id,
          references(:options,
            column: :id,
            name: "levels_options_option_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :level_id, :uuid, null: false
    end

    create unique_index(:levels_options, [:school_id, :level_id, :option_id],
             name: "levels_options_level_option_index"
           )

    create table(:levels, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:levels_options) do
      modify :level_id,
             references(:levels,
               column: :id,
               name: "levels_options_level_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:levels) do
      add :name, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec

      add :school_id,
          references(:schools,
            column: :id,
            name: "levels_school_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:levels, [:school_id, :name], name: "levels_unique_name_index")

    create table(:classrooms_students, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :access_status, :text, null: false, default: "allowed"
      add :access_note, :text
      add :access_set_at, :utc_datetime_usec
      add :archived_at, :utc_datetime_usec

      add :school_id,
          references(:schools,
            column: :id,
            name: "classrooms_students_school_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :classroom_id, :uuid, null: false
      add :student_id, :uuid, null: false
      add :access_set_by_id, :uuid
    end

    create unique_index(:classrooms_students, [:school_id, :classroom_id, :student_id],
             name: "classrooms_students_classroom_student_index"
           )

    create table(:classrooms, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:school_year_subject_teachers) do
      modify :classroom_id,
             references(:classrooms,
               column: :id,
               name: "school_year_subject_teachers_classroom_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :level_option_subject_id,
             references(:levels_options_subjects,
               column: :id,
               name: "school_year_subject_teachers_level_option_subject_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :teacher_id,
             references(:users,
               column: :id,
               name: "school_year_subject_teachers_teacher_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:marks) do
      modify :classroom_id,
             references(:classrooms,
               column: :id,
               name: "marks_classroom_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :sequence_id,
             references(:sequences,
               column: :id,
               name: "marks_sequence_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :level_option_subject_id,
             references(:levels_options_subjects,
               column: :id,
               name: "marks_level_option_subject_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:classrooms_students) do
      modify :classroom_id,
             references(:classrooms,
               column: :id,
               name: "classrooms_students_classroom_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :student_id,
             references(:students,
               column: :id,
               name: "classrooms_students_student_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :access_set_by_id,
             references(:users,
               column: :id,
               name: "classrooms_students_access_set_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:classrooms) do
      add :archived_at, :utc_datetime_usec

      add :school_id,
          references(:schools,
            column: :id,
            name: "classrooms_school_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :academic_year_id, :uuid, null: false
      add :level_option_id, :uuid, null: false
    end

    create unique_index(:classrooms, [:school_id, :academic_year_id, :level_option_id],
             name: "classrooms_name_index"
           )

    create table(:attendances, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :date, :date, null: false
      add :status, :text, null: false, default: "present"
      add :comment, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec

      add :school_id,
          references(:schools,
            column: :id,
            name: "attendances_school_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :student_id,
          references(:students,
            column: :id,
            name: "attendances_student_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :classroom_id,
          references(:classrooms,
            column: :id,
            name: "attendances_classroom_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:attendances, [:school_id, :student_id, :classroom_id, :date],
             name: "attendances_unique_attendance_index"
           )

    create table(:apc_lesson_plans, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :competence, :text, null: false
      add :prerequisites, :text
      add :situation_problem, :text
      add :learning_activities, :text
      add :resources, :text
      add :evaluation, :text
      add :remediation, :text
      add :duration_minutes, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec

      add :school_id,
          references(:schools,
            column: :id,
            name: "apc_lesson_plans_school_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :progression_entry_id,
          references(:progression_entries,
            column: :id,
            name: "apc_lesson_plans_progression_entry_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:academic_years, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:terms) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "terms_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:progression_plans) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "progression_plans_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :classroom_id,
             references(:classrooms,
               column: :id,
               name: "progression_plans_classroom_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :level_option_subject_id,
             references(:levels_options_subjects,
               column: :id,
               name: "progression_plans_level_option_subject_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :teacher_id,
             references(:users,
               column: :id,
               name: "progression_plans_teacher_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:classrooms) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "classrooms_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :level_option_id,
             references(:levels_options,
               column: :id,
               name: "classrooms_level_option_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:academic_years) do
      add :name, :text, null: false
      add :description, :text
      add :start_date, :date, null: false
      add :end_date, :date, null: false
      add :active, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec

      add :school_id,
          references(:schools,
            column: :id,
            name: "academic_years_school_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:academic_years, [:school_id, :name],
             name: "academic_years_unique_name_index"
           )
  end

  def down do
    drop constraint(:academic_years, "academic_years_school_id_fkey")

    drop_if_exists unique_index(:academic_years, [:school_id, :name],
                     name: "academic_years_unique_name_index"
                   )

    alter table(:academic_years) do
      remove :school_id
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :active
      remove :end_date
      remove :start_date
      remove :description
      remove :name
    end

    drop constraint(:classrooms, "classrooms_academic_year_id_fkey")

    drop constraint(:classrooms, "classrooms_level_option_id_fkey")

    alter table(:classrooms) do
      modify :level_option_id, :uuid
      modify :academic_year_id, :uuid
    end

    drop constraint(:progression_plans, "progression_plans_academic_year_id_fkey")

    drop constraint(:progression_plans, "progression_plans_classroom_id_fkey")

    drop constraint(:progression_plans, "progression_plans_level_option_subject_id_fkey")

    drop constraint(:progression_plans, "progression_plans_teacher_id_fkey")

    alter table(:progression_plans) do
      modify :teacher_id, :uuid
      modify :level_option_subject_id, :uuid
      modify :classroom_id, :uuid
      modify :academic_year_id, :uuid
    end

    drop constraint(:terms, "terms_academic_year_id_fkey")

    alter table(:terms) do
      modify :academic_year_id, :uuid
    end

    drop table(:academic_years)

    drop constraint(:apc_lesson_plans, "apc_lesson_plans_school_id_fkey")

    drop constraint(:apc_lesson_plans, "apc_lesson_plans_progression_entry_id_fkey")

    drop table(:apc_lesson_plans)

    drop constraint(:attendances, "attendances_school_id_fkey")

    drop constraint(:attendances, "attendances_student_id_fkey")

    drop constraint(:attendances, "attendances_classroom_id_fkey")

    drop_if_exists unique_index(:attendances, [:school_id, :student_id, :classroom_id, :date],
                     name: "attendances_unique_attendance_index"
                   )

    drop table(:attendances)

    drop constraint(:classrooms, "classrooms_school_id_fkey")

    drop_if_exists unique_index(:classrooms, [:school_id, :academic_year_id, :level_option_id],
                     name: "classrooms_name_index"
                   )

    alter table(:classrooms) do
      remove :level_option_id
      remove :academic_year_id
      remove :school_id
      remove :archived_at
    end

    drop constraint(:classrooms_students, "classrooms_students_classroom_id_fkey")

    drop constraint(:classrooms_students, "classrooms_students_student_id_fkey")

    drop constraint(:classrooms_students, "classrooms_students_access_set_by_id_fkey")

    alter table(:classrooms_students) do
      modify :access_set_by_id, :uuid
      modify :student_id, :uuid
      modify :classroom_id, :uuid
    end

    drop constraint(:marks, "marks_classroom_id_fkey")

    drop constraint(:marks, "marks_sequence_id_fkey")

    drop constraint(:marks, "marks_level_option_subject_id_fkey")

    alter table(:marks) do
      modify :level_option_subject_id, :uuid
      modify :sequence_id, :uuid
      modify :classroom_id, :uuid
    end

    drop constraint(
           :school_year_subject_teachers,
           "school_year_subject_teachers_classroom_id_fkey"
         )

    drop constraint(
           :school_year_subject_teachers,
           "school_year_subject_teachers_level_option_subject_id_fkey"
         )

    drop constraint(:school_year_subject_teachers, "school_year_subject_teachers_teacher_id_fkey")

    alter table(:school_year_subject_teachers) do
      modify :teacher_id, :uuid
      modify :level_option_subject_id, :uuid
      modify :classroom_id, :uuid
    end

    drop table(:classrooms)

    drop constraint(:classrooms_students, "classrooms_students_school_id_fkey")

    drop_if_exists unique_index(:classrooms_students, [:school_id, :classroom_id, :student_id],
                     name: "classrooms_students_classroom_student_index"
                   )

    drop table(:classrooms_students)

    drop constraint(:levels, "levels_school_id_fkey")

    drop_if_exists unique_index(:levels, [:school_id, :name], name: "levels_unique_name_index")

    alter table(:levels) do
      remove :school_id
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :name
    end

    drop constraint(:levels_options, "levels_options_level_id_fkey")

    alter table(:levels_options) do
      modify :level_id, :uuid
    end

    drop table(:levels)

    drop constraint(:levels_options, "levels_options_school_id_fkey")

    drop constraint(:levels_options, "levels_options_option_id_fkey")

    drop_if_exists unique_index(:levels_options, [:school_id, :level_id, :option_id],
                     name: "levels_options_level_option_index"
                   )

    alter table(:levels_options) do
      remove :level_id
      remove :option_id
      remove :school_id
    end

    drop constraint(:levels_options_subjects, "levels_options_subjects_level_option_id_fkey")

    drop constraint(:levels_options_subjects, "levels_options_subjects_subject_id_fkey")

    alter table(:levels_options_subjects) do
      modify :subject_id, :uuid
      modify :level_option_id, :uuid
    end

    drop table(:levels_options)

    drop_if_exists unique_index(:levels_options_subjects, [:level_option_id, :subject_id],
                     name: "levels_options_subjects_name_index"
                   )

    alter table(:levels_options_subjects) do
      remove :subject_id
      remove :level_option_id
      remove :coefficient
    end

    drop constraint(
           :sequences_subjects_objectives,
           "sequences_subjects_objectives_level_option_subject_id_fkey"
         )

    alter table(:sequences_subjects_objectives) do
      modify :level_option_subject_id, :uuid
    end

    drop table(:levels_options_subjects)

    drop constraint(:marks, "marks_school_id_fkey")

    drop constraint(:marks, "marks_student_id_fkey")

    drop_if_exists unique_index(
                     :marks,
                     [:school_id, :student_id, :level_option_subject_id, :sequence_id],
                     name: "marks_unique_mark_index"
                   )

    drop table(:marks)

    drop constraint(:options, "options_school_id_fkey")

    drop_if_exists unique_index(:options, [:school_id, :name], name: "options_unique_name_index")

    drop table(:options)

    drop constraint(:progression_entries, "progression_entries_school_id_fkey")

    drop constraint(:progression_entries, "progression_entries_progression_plan_id_fkey")

    drop constraint(:progression_entries, "progression_entries_term_id_fkey")

    drop constraint(:progression_entries, "progression_entries_sequence_id_fkey")

    alter table(:progression_entries) do
      remove :sequence_id
      remove :term_id
      remove :progression_plan_id
      remove :school_id
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :entry_type
      remove :planned_hours
      remove :planned_content
      remove :title
      remove :end_date
      remove :start_date
      remove :week_number
    end

    drop constraint(:teaching_logs, "teaching_logs_progression_entry_id_fkey")

    alter table(:teaching_logs) do
      modify :progression_entry_id, :uuid
    end

    drop table(:progression_entries)

    drop constraint(:progression_plans, "progression_plans_school_id_fkey")

    drop_if_exists unique_index(
                     :progression_plans,
                     [
                       :school_id,
                       :academic_year_id,
                       :classroom_id,
                       :level_option_subject_id,
                       :teacher_id
                     ],
                     name: "progression_plans_unique_teacher_progression_plan_index"
                   )

    drop table(:progression_plans)

    drop constraint(:school_year_subject_teachers, "school_year_subject_teachers_school_id_fkey")

    drop_if_exists unique_index(
                     :school_year_subject_teachers,
                     [:school_id, :classroom_id, :level_option_subject_id, :teacher_id],
                     name: "school_year_subject_teachers_unique_assignment_index"
                   )

    drop table(:school_year_subject_teachers)

    drop_if_exists unique_index(:schools, [:name], name: "schools_unique_name_index")

    alter table(:schools) do
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :sub_system
      remove :type
      remove :abbreviation
      remove :name
    end

    drop constraint(:sequences, "sequences_school_id_fkey")

    drop constraint(:sequences, "sequences_term_id_fkey")

    alter table(:sequences) do
      modify :term_id, :uuid
      modify :school_id, :uuid
    end

    drop constraint(
           :sequences_subjects_objectives,
           "sequences_subjects_objectives_school_id_fkey"
         )

    drop constraint(
           :sequences_subjects_objectives,
           "sequences_subjects_objectives_sequence_id_fkey"
         )

    alter table(:sequences_subjects_objectives) do
      modify :sequence_id, :uuid
      modify :school_id, :uuid
    end

    drop constraint(:students, "students_school_id_fkey")

    alter table(:students) do
      modify :school_id, :uuid
    end

    drop constraint(:subjects, "subjects_school_id_fkey")

    alter table(:subjects) do
      modify :school_id, :uuid
    end

    drop constraint(:teaching_logs, "teaching_logs_school_id_fkey")

    alter table(:teaching_logs) do
      modify :school_id, :uuid
    end

    drop constraint(:terms, "terms_school_id_fkey")

    alter table(:terms) do
      modify :school_id, :uuid
    end

    drop constraint(:users_schools, "users_schools_school_id_fkey")

    drop constraint(:users_schools, "users_schools_user_id_fkey")

    alter table(:users_schools) do
      modify :user_id, :uuid
      modify :school_id, :uuid
    end

    drop table(:schools)

    drop table(:sequences)

    drop_if_exists unique_index(
                     :sequences_subjects_objectives,
                     [:school_id, :sequence_id, :level_option_subject_id],
                     name: "sequences_subjects_objectives_unique_sequence_subject_index"
                   )

    drop table(:sequences_subjects_objectives)

    drop_if_exists unique_index(:students, [:school_id, :first_name, :last_name, :date_of_birth],
                     name: "students_unique_name_and_date_of_birth_index"
                   )

    drop table(:students)

    drop_if_exists unique_index(:subjects, [:school_id, :name],
                     name: "subjects_unique_name_index"
                   )

    drop table(:subjects)

    drop table(:teaching_logs)

    drop_if_exists unique_index(:terms, [:school_id, :name, :academic_year_id],
                     name: "terms_unique_name_index"
                   )

    drop table(:terms)

    execute("ALTER TABLE users DROP COLUMN IF EXISTS role")

    drop_if_exists unique_index(:users_schools, [:school_id, :user_id],
                     name: "users_schools_unique_user_school_index"
                   )

    drop table(:users_schools)
  end
end
