defmodule TeacherAssistant.Repo.Migrations.AddAcademicYear do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:academic_years, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :start_date, :date, null: false
      add :end_date, :date, null: false
      add :active, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :personal_workspace_id,
          references(:personal_workspaces,
            column: :id,
            name: "academic_years_personal_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:academic_years, [:personal_workspace_id, :name],
             name: "academic_years_unique_workspace_year_index"
           )
  end

  def down do
    drop constraint(:academic_years, "academic_years_personal_workspace_id_fkey")

    drop_if_exists unique_index(:academic_years, [:personal_workspace_id, :name],
                     name: "academic_years_unique_workspace_year_index"
                   )

    drop table(:academic_years)
  end
end
