defmodule TeacherAssistant.Repo.Migrations.AttendanceTenancy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:attendance_entries, [:enrollment_id, :date, :period_id],
                     name: "attendance_entries_unique_mark_index"
                   )

    drop constraint(:attendance_entries, "attendance_entries_period_id_fkey")

    create unique_index(:attendance_entries, [:workspace_id, :enrollment_id, :date, :period_id],
             name: "attendance_entries_unique_mark_index"
           )

    alter table(:attendance_entries) do
      modify :period_id,
             references(:periods,
               column: :id,
               name: "attendance_entries_period_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop_if_exists index(:attendance_entries, [:enrollment_id])

    create index(:attendance_entries, [:workspace_id, :enrollment_id])

    drop_if_exists index(:attendance_entries, [:period_id])

    create index(:attendance_entries, [:workspace_id, :period_id])

    drop_if_exists index(:attendance_entries, [:teaching_context_id])

    create index(:attendance_entries, [:workspace_id, :teaching_context_id])

    drop_if_exists index(:attendance_entries, [:workspace_id])

    create index(:attendance_entries, [:workspace_id])

    # NOTE: manually reordered from the autogenerated output — the generator
    # emitted `create index([:workspace_id, :date])` *before* the
    # `drop_if_exists` below, but that index already exists (created by the
    # original, pre-multitenancy `custom_indexes` migration with the same
    # auto-derived name), so the create must run only after the drop.
    drop_if_exists index(:attendance_entries, [:enrollment_id, :date])

    drop_if_exists index(:attendance_entries, [:workspace_id, :date])

    create index(:attendance_entries, [:workspace_id, :enrollment_id, :date])

    create index(:attendance_entries, [:workspace_id, :date])

    drop_if_exists unique_index(:periods, [:workspace_id, :position],
                     name: "periods_unique_period_position_index"
                   )

    create unique_index(:periods, [:workspace_id, :position],
             name: "periods_unique_period_position_index"
           )

    drop_if_exists index(:periods, [:workspace_id])

    create index(:periods, [:workspace_id])

    drop constraint(:timetable_slots, "timetable_slots_period_id_fkey")

    alter table(:timetable_slots) do
      modify :period_id,
             references(:periods,
               column: :id,
               name: "timetable_slots_period_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:timetable_slots, "timetable_slots_period_id_fkey")

    alter table(:timetable_slots) do
      modify :period_id,
             references(:periods,
               column: :id,
               name: "timetable_slots_period_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:periods, [:workspace_id])

    create index(:periods, [:workspace_id])

    drop_if_exists unique_index(:periods, [:workspace_id, :position],
                     name: "periods_unique_period_position_index"
                   )

    create unique_index(:periods, [:workspace_id, :position],
             name: "periods_unique_period_position_index"
           )

    # NOTE: manually reordered, mirroring the `up/0` fix above — the drops
    # must run before the creates that reuse the same auto-derived index name.
    drop_if_exists index(:attendance_entries, [:workspace_id, :date])

    drop_if_exists index(:attendance_entries, [:workspace_id, :enrollment_id, :date])

    create index(:attendance_entries, [:workspace_id, :date])

    create index(:attendance_entries, [:enrollment_id, :date])

    drop_if_exists index(:attendance_entries, [:workspace_id])

    create index(:attendance_entries, [:workspace_id])

    drop_if_exists index(:attendance_entries, [:workspace_id, :teaching_context_id])

    create index(:attendance_entries, [:teaching_context_id])

    drop_if_exists index(:attendance_entries, [:workspace_id, :period_id])

    create index(:attendance_entries, [:period_id])

    drop_if_exists index(:attendance_entries, [:workspace_id, :enrollment_id])

    create index(:attendance_entries, [:enrollment_id])

    drop constraint(:attendance_entries, "attendance_entries_period_id_fkey")

    alter table(:attendance_entries) do
      modify :period_id,
             references(:periods,
               column: :id,
               name: "attendance_entries_period_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop_if_exists unique_index(
                     :attendance_entries,
                     [:workspace_id, :enrollment_id, :date, :period_id],
                     name: "attendance_entries_unique_mark_index"
                   )

    create unique_index(:attendance_entries, [:enrollment_id, :date, :period_id],
             name: "attendance_entries_unique_mark_index"
           )
  end
end
