defmodule TeacherAssistant.Repo.Migrations.Phase1Cleanup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:school_profiles, [:workspace_id])

    create index(:school_profiles, [:owner_user_id])

    drop_if_exists index(
                     :teaching_contexts,
                     [:workspace_id, :academic_year_id, :class_group_id, :subject],
                     name: "teaching_contexts_unique_school_assignment"
                   )

    create index(
             :teaching_contexts,
             [:workspace_id, :academic_year_id, :class_group_id, :subject],
             name: "teaching_contexts_unique_school_assignment",
             unique: true
           )
  end

  def down do
    drop_if_exists index(
                     :teaching_contexts,
                     [:workspace_id, :academic_year_id, :class_group_id, :subject],
                     name: "teaching_contexts_unique_school_assignment"
                   )

    create index(
             :teaching_contexts,
             [:workspace_id, :academic_year_id, :class_group_id, :subject],
             name: "teaching_contexts_unique_school_assignment",
             unique: true,
             where: "teacher_user_id IS NOT NULL"
           )

    drop_if_exists index(:school_profiles, [:owner_user_id])

    drop_if_exists index(:school_profiles, [:workspace_id])
  end
end
