defmodule TeacherAssistant.Repo.Migrations.AveragingRules do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:school_profiles) do
      add :trimester_average_rule, :text, null: false, default: "mean_of_sequences"
      add :annual_average_rule, :text, null: false, default: "mean_of_sequences"
      add :average_rounding, :text, null: false, default: "hundredth"
      add :shared_ranks?, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:school_profiles) do
      remove :shared_ranks?
      remove :average_rounding
      remove :annual_average_rule
      remove :trimester_average_rule
    end
  end
end
