defmodule TeacherAssistant.Repo.Migrations.TimetablingTenancy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:timetable_slots, [:class_group_id, :day, :period_id],
                     name: "timetable_slots_unique_cell_index"
                   )

    create unique_index(:timetable_slots, [:workspace_id, :class_group_id, :day, :period_id],
             name: "timetable_slots_unique_cell_index"
           )

    drop_if_exists index(:timetable_slots, [:class_group_id])

    create index(:timetable_slots, [:workspace_id, :class_group_id])

    drop_if_exists index(:timetable_slots, [:teaching_context_id])

    # NOTE: manually reordered and de-duplicated from the autogenerated
    # output. The generator emitted `create index([:workspace_id,
    # :teaching_context_id])` here, then — after the `:period_id`/`:workspace_id`
    # pairs below — an identical second `create index([:workspace_id,
    # :teaching_context_id])` followed by a `drop_if_exists` of the same name.
    # That composite index already exists (created by the original,
    # pre-multitenancy `custom_indexes` migration, which this resource's
    # `custom_indexes` block still declares unchanged); the FK-index
    # conversion for `teaching_context_id` now auto-derives the exact same
    # name, so the generator's two `create`s for one uniquely-named index can
    # never both succeed in any order (verified: `mix ash.reset` fails with
    # `ERROR 42P07 duplicate_table` on the first `create` before this fix).
    # The drop below (moved up from its original position) clears the
    # pre-existing index so the single remaining `create` (the second,
    # now-redundant `create` is dropped) can (re)create it; net effect is a
    # harmless idempotent refresh of an index whose definition never changed.
    drop_if_exists index(:timetable_slots, [:workspace_id, :teaching_context_id])

    create index(:timetable_slots, [:workspace_id, :teaching_context_id])

    drop_if_exists index(:timetable_slots, [:period_id])

    create index(:timetable_slots, [:workspace_id, :period_id])

    drop_if_exists index(:timetable_slots, [:workspace_id])

    create index(:timetable_slots, [:workspace_id])
  end

  def down do
    drop_if_exists index(:timetable_slots, [:workspace_id])

    create index(:timetable_slots, [:workspace_id])

    drop_if_exists index(:timetable_slots, [:workspace_id, :period_id])

    create index(:timetable_slots, [:period_id])

    # NOTE: mirrors the up/0 fix above (reordered + de-duplicated) — undoes,
    # in reverse order, the single drop+create pair up/0 now performs for
    # `[:workspace_id, :teaching_context_id]`, then recreates the single-column
    # `:teaching_context_id` index up/0 dropped, restoring the original
    # dual-index (single-column FK index + composite custom index) state.
    drop_if_exists index(:timetable_slots, [:workspace_id, :teaching_context_id])

    create index(:timetable_slots, [:workspace_id, :teaching_context_id])

    create index(:timetable_slots, [:teaching_context_id])

    drop_if_exists index(:timetable_slots, [:workspace_id, :class_group_id])

    create index(:timetable_slots, [:class_group_id])

    drop_if_exists unique_index(
                     :timetable_slots,
                     [:workspace_id, :class_group_id, :day, :period_id],
                     name: "timetable_slots_unique_cell_index"
                   )

    create unique_index(:timetable_slots, [:class_group_id, :day, :period_id],
             name: "timetable_slots_unique_cell_index"
           )
  end
end
