defmodule TeacherAssistant.Repo.Migrations.RetireWorkspaceKind do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:workspaces, [:owner_user_id],
                     name: "workspaces_unique_owner_user_index"
                   )

    alter table(:workspaces) do
      remove :kind
      remove :owner_user_id
    end
  end

  def down do
    alter table(:workspaces) do
      add :owner_user_id,
          references(:users,
            column: :id,
            name: "workspaces_owner_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :kind, :text, null: false, default: "personal"
    end

    create unique_index(:workspaces, [:owner_user_id], name: "workspaces_unique_owner_user_index")
  end
end
