defmodule TeacherAssistant.Repo.Migrations.AddMarks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:marks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :score, :decimal

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :assessment_id,
          references(:assessments,
            column: :id,
            name: "marks_assessment_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :student_id,
          references(:students,
            column: :id,
            name: "marks_student_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:marks, [:assessment_id, :student_id], name: "marks_unique_mark_index")
  end

  def down do
    drop constraint(:marks, "marks_assessment_id_fkey")

    drop constraint(:marks, "marks_student_id_fkey")

    drop_if_exists unique_index(:marks, [:assessment_id, :student_id],
                     name: "marks_unique_mark_index"
                   )

    drop table(:marks)
  end
end
