defmodule TeacherAssistant.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:marks) do
      add :status, :text, null: false, default: "graded"
    end

    create constraint(:marks, :marks_status_score_check,
             check: """
               (status = 'graded') = (score IS NOT NULL)
             """
           )
  end

  def down do
    drop_if_exists constraint(:marks, :marks_status_score_check)

    alter table(:marks) do
      remove :status
    end
  end
end
