defmodule TeacherAssistant.Repo.Migrations.TenantCompositeFks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:academic_years, [:workspace_id, :id], unique: true)

    drop constraint(:assessments, "assessments_teaching_context_id_fkey")

    drop constraint(:assessments, "assessments_sequence_id_fkey")

    create index(:assessments, [:workspace_id, :id], unique: true)

    drop constraint(:attendance_entries, "attendance_entries_enrollment_id_fkey")

    drop constraint(:attendance_entries, "attendance_entries_period_id_fkey")

    drop constraint(:attendance_entries, "attendance_entries_teaching_context_id_fkey")

    drop constraint(:class_groups, "class_groups_academic_year_id_fkey")

    alter table(:class_groups) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "class_groups_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:class_groups, [:workspace_id, :id], unique: true)

    drop constraint(:combined_courses, "combined_courses_academic_year_id_fkey")

    alter table(:combined_courses) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "combined_courses_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:combined_courses, [:workspace_id, :id], unique: true)

    drop constraint(:conduct_marks, "conduct_marks_enrollment_id_fkey")

    drop constraint(:conduct_marks, "conduct_marks_sequence_id_fkey")

    drop constraint(:enrollments, "enrollments_student_id_fkey")

    drop constraint(:enrollments, "enrollments_class_group_id_fkey")

    alter table(:enrollments) do
      modify :class_group_id,
             references(:class_groups,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "enrollments_class_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:enrollments, "enrollments_academic_year_id_fkey")

    alter table(:enrollments) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "enrollments_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:enrollments, [:workspace_id, :id], unique: true)

    alter table(:attendance_entries) do
      modify :enrollment_id,
             references(:enrollments,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "attendance_entries_enrollment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:conduct_marks) do
      modify :enrollment_id,
             references(:enrollments,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "conduct_marks_enrollment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:fee_adjustments, "fee_adjustments_enrollment_id_fkey")

    alter table(:fee_adjustments) do
      modify :enrollment_id,
             references(:enrollments,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "fee_adjustments_enrollment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:fee_tranches, "fee_tranches_class_group_id_fkey")

    alter table(:fee_tranches) do
      modify :class_group_id,
             references(:class_groups,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "fee_tranches_class_group_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:lesson_plans, "lesson_plans_progression_entry_id_fkey")

    create index(:lesson_plans, [:workspace_id, :id], unique: true)

    drop constraint(:lesson_steps, "lesson_steps_lesson_plan_id_fkey")

    alter table(:lesson_steps) do
      modify :lesson_plan_id,
             references(:lesson_plans,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "lesson_steps_lesson_plan_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:marks, "marks_assessment_id_fkey")

    alter table(:marks) do
      modify :assessment_id,
             references(:assessments,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "marks_assessment_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:marks, "marks_student_id_fkey")

    drop constraint(:payments, "payments_enrollment_id_fkey")

    alter table(:payments) do
      modify :enrollment_id,
             references(:enrollments,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "payments_enrollment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:periods, [:workspace_id, :id], unique: true)

    alter table(:attendance_entries) do
      modify :period_id,
             references(:periods,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "attendance_entries_period_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:progression_entries, "progression_entries_progression_plan_id_fkey")

    drop constraint(:progression_entries, "progression_entries_sequence_id_fkey")

    drop constraint(:progression_entries, "progression_entries_progression_module_id_fkey")

    create index(:progression_entries, [:workspace_id, :id], unique: true)

    alter table(:lesson_plans) do
      modify :progression_entry_id,
             references(:progression_entries,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "lesson_plans_progression_entry_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:progression_modules, "progression_modules_progression_plan_id_fkey")

    drop constraint(:progression_modules, "progression_modules_sequence_id_fkey")

    create index(:progression_modules, [:workspace_id, :id], unique: true)

    alter table(:progression_entries) do
      modify :progression_module_id,
             references(:progression_modules,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "progression_entries_progression_module_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:progression_plans, "progression_plans_teaching_context_id_fkey")

    drop constraint(:progression_plans, "progression_plans_combined_course_id_fkey")

    alter table(:progression_plans) do
      modify :combined_course_id,
             references(:combined_courses,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :simple,
               name: "progression_plans_combined_course_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: {:nilify, [:combined_course_id]}
             )
    end

    drop constraint(:progression_plans, "progression_plans_academic_year_id_fkey")

    alter table(:progression_plans) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "progression_plans_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:progression_plans, [:workspace_id, :id], unique: true)

    alter table(:progression_entries) do
      modify :progression_plan_id,
             references(:progression_plans,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "progression_entries_progression_plan_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:progression_modules) do
      modify :progression_plan_id,
             references(:progression_plans,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "progression_modules_progression_plan_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:sanction_entries, "sanction_entries_enrollment_id_fkey")

    alter table(:sanction_entries) do
      modify :enrollment_id,
             references(:enrollments,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "sanction_entries_enrollment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:sequences, "sequences_term_id_fkey")

    create index(:sequences, [:workspace_id, :id], unique: true)

    alter table(:assessments) do
      modify :sequence_id,
             references(:sequences,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "assessments_sequence_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:conduct_marks) do
      modify :sequence_id,
             references(:sequences,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "conduct_marks_sequence_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:progression_entries) do
      modify :sequence_id,
             references(:sequences,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :simple,
               name: "progression_entries_sequence_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:progression_modules) do
      modify :sequence_id,
             references(:sequences,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :simple,
               name: "progression_modules_sequence_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:students, [:workspace_id, :id], unique: true)

    alter table(:enrollments) do
      modify :student_id,
             references(:students,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "enrollments_student_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:marks) do
      modify :student_id,
             references(:students,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "marks_student_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:teaching_contexts, "teaching_contexts_academic_year_id_fkey")

    alter table(:teaching_contexts) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "teaching_contexts_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:teaching_contexts, "teaching_contexts_class_group_id_fkey")

    alter table(:teaching_contexts) do
      modify :class_group_id,
             references(:class_groups,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "teaching_contexts_class_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:teaching_contexts, "teaching_contexts_combined_course_id_fkey")

    alter table(:teaching_contexts) do
      modify :combined_course_id,
             references(:combined_courses,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :simple,
               name: "teaching_contexts_combined_course_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: {:nilify, [:combined_course_id]}
             )
    end

    create index(:teaching_contexts, [:workspace_id, :id], unique: true)

    alter table(:assessments) do
      modify :teaching_context_id,
             references(:teaching_contexts,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "assessments_teaching_context_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:attendance_entries) do
      modify :teaching_context_id,
             references(:teaching_contexts,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :simple,
               name: "attendance_entries_teaching_context_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:progression_plans) do
      modify :teaching_context_id,
             references(:teaching_contexts,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :simple,
               name: "progression_plans_teaching_context_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:teaching_log_entries, "teaching_log_entries_progression_entry_id_fkey")

    alter table(:teaching_log_entries) do
      modify :progression_entry_id,
             references(:progression_entries,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :simple,
               name: "teaching_log_entries_progression_entry_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:terms, "terms_academic_year_id_fkey")

    alter table(:terms) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "terms_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:terms, [:workspace_id, :id], unique: true)

    alter table(:sequences) do
      modify :term_id,
             references(:terms,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "sequences_term_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:timetable_slots, "timetable_slots_class_group_id_fkey")

    alter table(:timetable_slots) do
      modify :class_group_id,
             references(:class_groups,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "timetable_slots_class_group_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:timetable_slots, "timetable_slots_teaching_context_id_fkey")

    alter table(:timetable_slots) do
      modify :teaching_context_id,
             references(:teaching_contexts,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "timetable_slots_teaching_context_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:timetable_slots, "timetable_slots_period_id_fkey")

    alter table(:timetable_slots) do
      modify :period_id,
             references(:periods,
               column: :id,
               with: [workspace_id: :workspace_id],
               match: :full,
               name: "timetable_slots_period_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:timetable_slots, "timetable_slots_period_id_fkey")

    drop constraint(:timetable_slots, "timetable_slots_teaching_context_id_fkey")

    drop constraint(:timetable_slots, "timetable_slots_class_group_id_fkey")

    alter table(:timetable_slots) do
      modify :period_id,
             references(:periods,
               column: :id,
               name: "timetable_slots_period_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:timetable_slots) do
      modify :teaching_context_id,
             references(:teaching_contexts,
               column: :id,
               name: "timetable_slots_teaching_context_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:timetable_slots) do
      modify :class_group_id,
             references(:class_groups,
               column: :id,
               name: "timetable_slots_class_group_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:sequences, "sequences_term_id_fkey")

    alter table(:sequences) do
      modify :term_id,
             references(:terms,
               column: :id,
               name: "sequences_term_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:terms, [:workspace_id, :id])

    drop constraint(:terms, "terms_academic_year_id_fkey")

    alter table(:terms) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "terms_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:teaching_log_entries, "teaching_log_entries_progression_entry_id_fkey")

    alter table(:teaching_log_entries) do
      modify :progression_entry_id,
             references(:progression_entries,
               column: :id,
               name: "teaching_log_entries_progression_entry_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:progression_plans, "progression_plans_academic_year_id_fkey")

    drop constraint(:progression_plans, "progression_plans_combined_course_id_fkey")

    drop constraint(:progression_plans, "progression_plans_teaching_context_id_fkey")

    alter table(:progression_plans) do
      modify :teaching_context_id,
             references(:teaching_contexts,
               column: :id,
               name: "progression_plans_teaching_context_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:attendance_entries, "attendance_entries_teaching_context_id_fkey")

    drop constraint(:attendance_entries, "attendance_entries_period_id_fkey")

    drop constraint(:attendance_entries, "attendance_entries_enrollment_id_fkey")

    alter table(:attendance_entries) do
      modify :teaching_context_id,
             references(:teaching_contexts,
               column: :id,
               name: "attendance_entries_teaching_context_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:assessments, "assessments_sequence_id_fkey")

    drop constraint(:assessments, "assessments_teaching_context_id_fkey")

    alter table(:assessments) do
      modify :teaching_context_id,
             references(:teaching_contexts,
               column: :id,
               name: "assessments_teaching_context_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:teaching_contexts, [:workspace_id, :id])

    drop constraint(:teaching_contexts, "teaching_contexts_combined_course_id_fkey")

    drop constraint(:teaching_contexts, "teaching_contexts_class_group_id_fkey")

    drop constraint(:teaching_contexts, "teaching_contexts_academic_year_id_fkey")

    alter table(:teaching_contexts) do
      modify :combined_course_id,
             references(:combined_courses,
               column: :id,
               name: "teaching_contexts_combined_course_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:teaching_contexts) do
      modify :class_group_id,
             references(:class_groups,
               column: :id,
               name: "teaching_contexts_class_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:teaching_contexts) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "teaching_contexts_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:marks, "marks_student_id_fkey")

    drop constraint(:marks, "marks_assessment_id_fkey")

    alter table(:marks) do
      modify :student_id,
             references(:students,
               column: :id,
               name: "marks_student_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:enrollments, "enrollments_academic_year_id_fkey")

    drop constraint(:enrollments, "enrollments_class_group_id_fkey")

    drop constraint(:enrollments, "enrollments_student_id_fkey")

    alter table(:enrollments) do
      modify :student_id,
             references(:students,
               column: :id,
               name: "enrollments_student_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop_if_exists index(:students, [:workspace_id, :id])

    drop constraint(:progression_modules, "progression_modules_sequence_id_fkey")

    drop constraint(:progression_modules, "progression_modules_progression_plan_id_fkey")

    alter table(:progression_modules) do
      modify :sequence_id,
             references(:sequences,
               column: :id,
               name: "progression_modules_sequence_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:progression_entries, "progression_entries_progression_module_id_fkey")

    drop constraint(:progression_entries, "progression_entries_sequence_id_fkey")

    drop constraint(:progression_entries, "progression_entries_progression_plan_id_fkey")

    alter table(:progression_entries) do
      modify :sequence_id,
             references(:sequences,
               column: :id,
               name: "progression_entries_sequence_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:conduct_marks, "conduct_marks_sequence_id_fkey")

    drop constraint(:conduct_marks, "conduct_marks_enrollment_id_fkey")

    alter table(:conduct_marks) do
      modify :sequence_id,
             references(:sequences,
               column: :id,
               name: "conduct_marks_sequence_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:assessments) do
      modify :sequence_id,
             references(:sequences,
               column: :id,
               name: "assessments_sequence_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:sequences, [:workspace_id, :id])

    drop constraint(:sanction_entries, "sanction_entries_enrollment_id_fkey")

    alter table(:sanction_entries) do
      modify :enrollment_id,
             references(:enrollments,
               column: :id,
               name: "sanction_entries_enrollment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:progression_modules) do
      modify :progression_plan_id,
             references(:progression_plans,
               column: :id,
               name: "progression_modules_progression_plan_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:progression_entries) do
      modify :progression_plan_id,
             references(:progression_plans,
               column: :id,
               name: "progression_entries_progression_plan_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:progression_plans, [:workspace_id, :id])

    alter table(:progression_plans) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "progression_plans_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:progression_plans) do
      modify :combined_course_id,
             references(:combined_courses,
               column: :id,
               name: "progression_plans_combined_course_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:progression_entries) do
      modify :progression_module_id,
             references(:progression_modules,
               column: :id,
               name: "progression_entries_progression_module_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:progression_modules, [:workspace_id, :id])

    drop constraint(:lesson_plans, "lesson_plans_progression_entry_id_fkey")

    alter table(:lesson_plans) do
      modify :progression_entry_id,
             references(:progression_entries,
               column: :id,
               name: "lesson_plans_progression_entry_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:progression_entries, [:workspace_id, :id])

    alter table(:attendance_entries) do
      modify :period_id,
             references(:periods,
               column: :id,
               name: "attendance_entries_period_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop_if_exists index(:periods, [:workspace_id, :id])

    drop constraint(:payments, "payments_enrollment_id_fkey")

    alter table(:payments) do
      modify :enrollment_id,
             references(:enrollments,
               column: :id,
               name: "payments_enrollment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:marks) do
      modify :assessment_id,
             references(:assessments,
               column: :id,
               name: "marks_assessment_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:lesson_steps, "lesson_steps_lesson_plan_id_fkey")

    alter table(:lesson_steps) do
      modify :lesson_plan_id,
             references(:lesson_plans,
               column: :id,
               name: "lesson_steps_lesson_plan_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:lesson_plans, [:workspace_id, :id])

    drop constraint(:fee_tranches, "fee_tranches_class_group_id_fkey")

    alter table(:fee_tranches) do
      modify :class_group_id,
             references(:class_groups,
               column: :id,
               name: "fee_tranches_class_group_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:fee_adjustments, "fee_adjustments_enrollment_id_fkey")

    alter table(:fee_adjustments) do
      modify :enrollment_id,
             references(:enrollments,
               column: :id,
               name: "fee_adjustments_enrollment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:conduct_marks) do
      modify :enrollment_id,
             references(:enrollments,
               column: :id,
               name: "conduct_marks_enrollment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:attendance_entries) do
      modify :enrollment_id,
             references(:enrollments,
               column: :id,
               name: "attendance_entries_enrollment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop_if_exists index(:enrollments, [:workspace_id, :id])

    alter table(:enrollments) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "enrollments_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:enrollments) do
      modify :class_group_id,
             references(:class_groups,
               column: :id,
               name: "enrollments_class_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:combined_courses, [:workspace_id, :id])

    drop constraint(:combined_courses, "combined_courses_academic_year_id_fkey")

    alter table(:combined_courses) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "combined_courses_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:class_groups, [:workspace_id, :id])

    drop constraint(:class_groups, "class_groups_academic_year_id_fkey")

    alter table(:class_groups) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "class_groups_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:assessments, [:workspace_id, :id])

    drop_if_exists index(:academic_years, [:workspace_id, :id])
  end
end
