defmodule TeacherAssistant.Repo.Migrations.TimetablingTenancy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:timetable_slots, [:class_group_id, :day, :period_id],
                     name: "timetable_slots_unique_cell_index"
                   )

    create unique_index(:timetable_slots, [:workspace_id, :class_group_id, :day, :period_id],
             name: "timetable_slots_unique_cell_index"
           )

    drop_if_exists index(:timetable_slots, [:class_group_id])

    create index(:timetable_slots, [:workspace_id, :class_group_id])

    drop_if_exists index(:timetable_slots, [:teaching_context_id])

    # NOTE: manually reordered from the autogenerated output — the index name
    # `timetable_slots_workspace_id_teaching_context_id_index` was first
    # created by `20260923231628_constraints_and_indexes.exs` (the resource's
    # now-removed `custom_indexes` entry); the tenant-prefixed FK index of the
    # same name (from the `teaching_context` reference under multitenancy)
    # must be created only after that old one is dropped, so the
    # `drop_if_exists` below is moved ahead of the `create`.
    drop_if_exists index(:timetable_slots, [:workspace_id, :teaching_context_id])

    create index(:timetable_slots, [:workspace_id, :teaching_context_id])

    drop_if_exists index(:timetable_slots, [:period_id])

    create index(:timetable_slots, [:workspace_id, :period_id])

    drop_if_exists index(:timetable_slots, [:workspace_id])

    create index(:timetable_slots, [:workspace_id])
  end

  def down do
    drop_if_exists index(:timetable_slots, [:workspace_id])

    create index(:timetable_slots, [:workspace_id])

    drop_if_exists index(:timetable_slots, [:workspace_id, :period_id])

    create index(:timetable_slots, [:period_id])

    # NOTE: mirrors the up/0 reorder above — undoes, in reverse order, the
    # drop_if_exists+create pair up/0 now performs for `[:workspace_id,
    # :teaching_context_id]`, then recreates the single-column
    # `:teaching_context_id` index up/0 dropped.
    drop_if_exists index(:timetable_slots, [:workspace_id, :teaching_context_id])

    create index(:timetable_slots, [:workspace_id, :teaching_context_id])

    create index(:timetable_slots, [:teaching_context_id])

    drop_if_exists index(:timetable_slots, [:workspace_id, :class_group_id])

    create index(:timetable_slots, [:class_group_id])

    drop_if_exists unique_index(
                     :timetable_slots,
                     [:workspace_id, :class_group_id, :day, :period_id],
                     name: "timetable_slots_unique_cell_index"
                   )

    create unique_index(:timetable_slots, [:class_group_id, :day, :period_id],
             name: "timetable_slots_unique_cell_index"
           )
  end
end
