defmodule TeacherAssistant.Repo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:progression_plans, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :title, :text, null: false
      add :status, :text, default: "draft"
      add :template, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :teaching_context_id,
          references(:teaching_contexts,
            column: :id,
            name: "progression_plans_teaching_context_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :academic_year_id,
          references(:academic_years,
            column: :id,
            name: "progression_plans_academic_year_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :personal_workspace_id,
          references(:personal_workspaces,
            column: :id,
            name: "progression_plans_personal_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:progression_plans, "progression_plans_teaching_context_id_fkey")

    drop constraint(:progression_plans, "progression_plans_academic_year_id_fkey")

    drop constraint(:progression_plans, "progression_plans_personal_workspace_id_fkey")

    drop table(:progression_plans)
  end
end
