defmodule TeacherAssistant.Repo.Migrations.DropPersonalTeachingContextIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(
                     :teaching_contexts,
                     [:workspace_id, :academic_year_id, :subject, :level, :serie],
                     name: "teaching_contexts_unique_personal_context"
                   )
  end

  def down do
    create index(:teaching_contexts, [:workspace_id, :academic_year_id, :subject, :level, :serie],
             name: "teaching_contexts_unique_personal_context",
             unique: true,
             where: "teacher_user_id IS NULL",
             nulls_distinct: false
           )
  end
end
