defmodule TeacherAssistant.Repo.Migrations.TeachingPivotsAndEnums do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:teaching_contexts) do
      modify :class_group_id, :uuid, null: false
      modify :teacher_user_id, :uuid, null: false
      remove :annual_hours
      remove :target_module_count
      remove :target_lesson_count
    end
  end

  def down do
    alter table(:teaching_contexts) do
      add :target_lesson_count, :bigint
      add :target_module_count, :bigint
      add :annual_hours, :decimal
      modify :teacher_user_id, :uuid, null: true
      modify :class_group_id, :uuid, null: true
    end
  end
end
