defmodule TeacherAssistant.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:teaching_contexts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :subject, :text, null: false
      add :level, :text, null: false
      add :serie, :text
      add :subsystem, :text, null: false
      add :weekly_hours, :bigint, default: 4

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :personal_workspace_id,
          references(:personal_workspaces,
            column: :id,
            name: "teaching_contexts_personal_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :academic_year_id,
          references(:academic_years,
            column: :id,
            name: "teaching_contexts_academic_year_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(
             :teaching_contexts,
             [:personal_workspace_id, :academic_year_id, :subject, :level, :serie],
             name: "teaching_contexts_unique_context_index"
           )
  end

  def down do
    drop constraint(:teaching_contexts, "teaching_contexts_personal_workspace_id_fkey")

    drop constraint(:teaching_contexts, "teaching_contexts_academic_year_id_fkey")

    drop_if_exists unique_index(
                     :teaching_contexts,
                     [:personal_workspace_id, :academic_year_id, :subject, :level, :serie],
                     name: "teaching_contexts_unique_context_index"
                   )

    drop table(:teaching_contexts)
  end
end
