defmodule TeacherAssistant.Repo.Migrations.P27Period do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:periods, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :position, :bigint, null: false
      add :label, :text, null: false
      add :start_time, :time, null: false
      add :end_time, :time, null: false
      add :kind, :text, null: false, default: "lesson"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "periods_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:periods, [:workspace_id, :position],
             name: "periods_unique_period_position_index"
           )
  end

  def down do
    drop constraint(:periods, "periods_workspace_id_fkey")

    drop_if_exists unique_index(:periods, [:workspace_id, :position],
                     name: "periods_unique_period_position_index"
                   )

    drop table(:periods)
  end
end
