defmodule TeacherAssistant.Repo.Migrations.AddProgressionModules do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:progression_modules, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :title, :text, null: false
      add :position, :bigint, null: false
      add :default?, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :progression_plan_id,
          references(:progression_plans,
            column: :id,
            name: "progression_modules_progression_plan_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    alter table(:progression_entries) do
      add :progression_module_id,
          references(:progression_modules,
            column: :id,
            name: "progression_entries_progression_module_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:progression_entries, "progression_entries_progression_module_id_fkey")

    alter table(:progression_entries) do
      remove :progression_module_id
    end

    drop constraint(:progression_modules, "progression_modules_progression_plan_id_fkey")

    drop table(:progression_modules)
  end
end
