defmodule TeacherAssistant.Repo.Migrations.OrganizationTenancy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:academic_years, [:workspace_id, :name],
                     name: "academic_years_unique_workspace_year_index"
                   )

    create unique_index(:academic_years, [:workspace_id, :name],
             name: "academic_years_unique_workspace_year_index"
           )

    drop_if_exists index(:academic_years, [:workspace_id])

    create index(:academic_years, [:workspace_id])

    drop_if_exists index(:academic_years, [:workspace_id],
                     name: "academic_years_one_active_per_workspace"
                   )

    create index(:academic_years, [:workspace_id],
             name: "academic_years_one_active_per_workspace",
             unique: true,
             where: "active"
           )

    drop constraint(:assessments, "assessments_sequence_id_fkey")

    alter table(:assessments) do
      modify :sequence_id,
             references(:sequences,
               column: :id,
               name: "assessments_sequence_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:class_groups, "class_groups_academic_year_id_fkey")

    alter table(:class_groups) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "class_groups_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:combined_courses, "combined_courses_academic_year_id_fkey")

    alter table(:combined_courses) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "combined_courses_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:conduct_marks, "conduct_marks_sequence_id_fkey")

    alter table(:conduct_marks) do
      modify :sequence_id,
             references(:sequences,
               column: :id,
               name: "conduct_marks_sequence_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:enrollments, "enrollments_academic_year_id_fkey")

    alter table(:enrollments) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "enrollments_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:progression_entries, "progression_entries_sequence_id_fkey")

    alter table(:progression_entries) do
      modify :sequence_id,
             references(:sequences,
               column: :id,
               name: "progression_entries_sequence_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:progression_modules, "progression_modules_sequence_id_fkey")

    alter table(:progression_modules) do
      modify :sequence_id,
             references(:sequences,
               column: :id,
               name: "progression_modules_sequence_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:progression_plans, "progression_plans_academic_year_id_fkey")

    alter table(:progression_plans) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "progression_plans_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:sequences, "sequences_term_id_fkey")

    alter table(:sequences) do
      modify :term_id,
             references(:terms,
               column: :id,
               name: "sequences_term_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:sequences, [:term_id])

    create index(:sequences, [:workspace_id, :term_id])

    drop_if_exists index(:sequences, [:workspace_id])

    create index(:sequences, [:workspace_id])

    drop constraint(:teaching_contexts, "teaching_contexts_academic_year_id_fkey")

    alter table(:teaching_contexts) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "teaching_contexts_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists unique_index(:terms, [:academic_year_id, :position],
                     name: "terms_unique_year_term_index"
                   )

    drop constraint(:terms, "terms_academic_year_id_fkey")

    create unique_index(:terms, [:workspace_id, :academic_year_id, :position],
             name: "terms_unique_year_term_index"
           )

    alter table(:terms) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "terms_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:terms, [:academic_year_id])

    create index(:terms, [:workspace_id, :academic_year_id])

    drop_if_exists index(:terms, [:workspace_id])

    create index(:terms, [:workspace_id])
  end

  def down do
    drop_if_exists index(:terms, [:workspace_id])

    create index(:terms, [:workspace_id])

    drop_if_exists index(:terms, [:workspace_id, :academic_year_id])

    create index(:terms, [:academic_year_id])

    drop constraint(:terms, "terms_academic_year_id_fkey")

    alter table(:terms) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "terms_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists unique_index(:terms, [:workspace_id, :academic_year_id, :position],
                     name: "terms_unique_year_term_index"
                   )

    create unique_index(:terms, [:academic_year_id, :position],
             name: "terms_unique_year_term_index"
           )

    drop constraint(:teaching_contexts, "teaching_contexts_academic_year_id_fkey")

    alter table(:teaching_contexts) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "teaching_contexts_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:sequences, [:workspace_id])

    create index(:sequences, [:workspace_id])

    drop_if_exists index(:sequences, [:workspace_id, :term_id])

    create index(:sequences, [:term_id])

    drop constraint(:sequences, "sequences_term_id_fkey")

    alter table(:sequences) do
      modify :term_id,
             references(:terms,
               column: :id,
               name: "sequences_term_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:progression_plans, "progression_plans_academic_year_id_fkey")

    alter table(:progression_plans) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "progression_plans_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:progression_modules, "progression_modules_sequence_id_fkey")

    alter table(:progression_modules) do
      modify :sequence_id,
             references(:sequences,
               column: :id,
               name: "progression_modules_sequence_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:progression_entries, "progression_entries_sequence_id_fkey")

    alter table(:progression_entries) do
      modify :sequence_id,
             references(:sequences,
               column: :id,
               name: "progression_entries_sequence_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:enrollments, "enrollments_academic_year_id_fkey")

    alter table(:enrollments) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "enrollments_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:conduct_marks, "conduct_marks_sequence_id_fkey")

    alter table(:conduct_marks) do
      modify :sequence_id,
             references(:sequences,
               column: :id,
               name: "conduct_marks_sequence_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:combined_courses, "combined_courses_academic_year_id_fkey")

    alter table(:combined_courses) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "combined_courses_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:class_groups, "class_groups_academic_year_id_fkey")

    alter table(:class_groups) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "class_groups_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:assessments, "assessments_sequence_id_fkey")

    alter table(:assessments) do
      modify :sequence_id,
             references(:sequences,
               column: :id,
               name: "assessments_sequence_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:academic_years, [:workspace_id],
                     name: "academic_years_one_active_per_workspace"
                   )

    create index(:academic_years, [:workspace_id],
             name: "academic_years_one_active_per_workspace",
             unique: true,
             where: "active"
           )

    drop_if_exists index(:academic_years, [:workspace_id])

    create index(:academic_years, [:workspace_id])

    drop_if_exists unique_index(:academic_years, [:workspace_id, :name],
                     name: "academic_years_unique_workspace_year_index"
                   )

    create unique_index(:academic_years, [:workspace_id, :name],
             name: "academic_years_unique_workspace_year_index"
           )
  end
end
