defmodule TeacherAssistant.Repo.Migrations.P22Enrollments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:students) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "students_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: true
    end

    execute("""
    UPDATE students SET workspace_id = cg.workspace_id
    FROM class_groups cg WHERE cg.id = students.class_group_id
    """)

    alter table(:students) do
      modify :workspace_id, :uuid, null: false
    end

    create table(:enrollments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :status, :text, null: false, default: "inscription"
      add :repeater, :boolean, null: false, default: false

      add :student_id,
          references(:students,
            column: :id,
            name: "enrollments_student_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :class_group_id,
          references(:class_groups,
            column: :id,
            name: "enrollments_class_group_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :academic_year_id,
          references(:academic_years,
            column: :id,
            name: "enrollments_academic_year_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "enrollments_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    execute("""
    INSERT INTO enrollments
      (id, status, repeater, student_id, class_group_id, academic_year_id, workspace_id,
       inserted_at, updated_at)
    SELECT uuid_generate_v7(), 'inscription', s.repeater, s.id, s.class_group_id,
           cg.academic_year_id, cg.workspace_id, now(), now()
    FROM students s JOIN class_groups cg ON cg.id = s.class_group_id
    """)

    create unique_index(:enrollments, [:student_id, :academic_year_id],
             name: "enrollments_unique_enrollment_per_year_index"
           )

    create unique_index(:students, [:workspace_id, :matricule],
             name: "students_unique_matricule_index",
             where: "matricule IS NOT NULL"
           )

    alter table(:students) do
      remove :class_group_id
      remove :repeater
    end
  end

  def down do
    raise "irreversible: enrollment refactor"
  end
end
