defmodule TeacherAssistant.Repo.Migrations.AddMembershipStatusToSchoolInvitations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:school_invitations) do
      add :membership_status, :text
    end
  end

  def down do
    alter table(:school_invitations) do
      remove :membership_status
    end
  end
end
