defmodule TeacherAssistant.Repo.Migrations.AddCombinedCourses do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:combined_courses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :subject, :text, null: false
      add :label, :text, null: false

      add :teacher_user_id,
          references(:users,
            column: :id,
            name: "combined_courses_teacher_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "combined_courses_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :academic_year_id,
          references(:academic_years,
            column: :id,
            name: "combined_courses_academic_year_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:combined_courses, "combined_courses_academic_year_id_fkey")

    drop constraint(:combined_courses, "combined_courses_workspace_id_fkey")

    drop constraint(:combined_courses, "combined_courses_teacher_user_id_fkey")

    drop table(:combined_courses)
  end
end
