defmodule TeacherAssistant.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:terms, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :position, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :academic_year_id,
          references(:academic_years,
            column: :id,
            name: "terms_academic_year_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:terms, [:academic_year_id, :position],
             name: "terms_unique_year_term_index"
           )

    create table(:sequences, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :number, :bigint, null: false
      add :position_in_term, :bigint, null: false
      add :start_date, :date, null: false
      add :end_date, :date, null: false
      add :integration_week, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :term_id,
          references(:terms,
            column: :id,
            name: "sequences_term_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:sequences, "sequences_term_id_fkey")

    drop table(:sequences)

    drop constraint(:terms, "terms_academic_year_id_fkey")

    drop_if_exists unique_index(:terms, [:academic_year_id, :position],
                     name: "terms_unique_year_term_index"
                   )

    drop table(:terms)
  end
end
