defmodule TeacherAssistant.Repo.Migrations.AddEntryCompletedAndModuleSequence do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:progression_modules) do
      add :sequence_id,
          references(:sequences,
            column: :id,
            name: "progression_modules_sequence_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:progression_entries) do
      add :completed?, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:progression_entries) do
      remove :completed?
    end

    drop constraint(:progression_modules, "progression_modules_sequence_id_fkey")

    alter table(:progression_modules) do
      remove :sequence_id
    end
  end
end
