defmodule TeacherAssistant.Repo.Migrations.P23Coefficient do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:teaching_contexts) do
      add :coefficient, :decimal, null: false, default: "1"
    end
  end

  def down do
    alter table(:teaching_contexts) do
      remove :coefficient
    end
  end
end
