defmodule TeacherAssistant.Repo.Migrations.CalendarMilestones do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sequences) do
      add :entry_deadline, :date
    end

    create constraint(:sequences, :sequences_entry_deadline_after_end_check,
             check: """
               entry_deadline IS NULL OR entry_deadline >= end_date
             """
           )

    alter table(:terms) do
      add :class_council_date, :date
    end
  end

  def down do
    alter table(:terms) do
      remove :class_council_date
    end

    drop_if_exists constraint(:sequences, :sequences_entry_deadline_after_end_check)

    alter table(:sequences) do
      remove :entry_deadline
    end
  end
end
