defmodule TeacherAssistant.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :email, :citext, null: false
      add :role, :text, default: "teacher"
      add :hashed_password, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:teaching_log_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :taught_on, :date, null: false
      add :taught_hours, :decimal, null: false, default: "1.0"
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :lesson_plan_entry_id, :uuid, null: false
    end

    create table(:personal_workspaces, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_user_id,
          references(:users,
            column: :id,
            name: "personal_workspaces_owner_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:personal_workspaces, [:owner_user_id],
             name: "personal_workspaces_unique_owner_user_index"
           )

    create table(:personal_classrooms, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :class_label, :text, null: false
      add :subject, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :personal_workspace_id,
          references(:personal_workspaces,
            column: :id,
            name: "personal_classrooms_personal_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :academic_year_id, :uuid, null: false
    end

    create unique_index(
             :personal_classrooms,
             [:personal_workspace_id, :academic_year_id, :class_label, :subject],
             name: "personal_classrooms_unique_workspace_class_subject_year_index"
           )

    create table(:lesson_plan_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:teaching_log_entries) do
      modify :lesson_plan_entry_id,
             references(:lesson_plan_entries,
               column: :id,
               name: "teaching_log_entries_lesson_plan_entry_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:lesson_plan_entries) do
      add :title, :text, null: false
      add :planned_on, :date, null: false
      add :planned_hours, :decimal, null: false, default: "1.0"
      add :objectives, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :personal_classroom_id,
          references(:personal_classrooms,
            column: :id,
            name: "lesson_plan_entries_personal_classroom_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:learners, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :first_name, :text, null: false
      add :last_name, :text, null: false
      add :identifier, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :personal_classroom_id,
          references(:personal_classrooms,
            column: :id,
            name: "learners_personal_classroom_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:attendance_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :date, :date, null: false
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :personal_classroom_id,
          references(:personal_classrooms,
            column: :id,
            name: "attendance_sessions_personal_classroom_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:attendance_sessions, [:personal_classroom_id, :date],
             name: "attendance_sessions_unique_classroom_date_index"
           )

    create table(:attendance_records, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :status, :text, null: false, default: "present"
      add :note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :attendance_session_id,
          references(:attendance_sessions,
            column: :id,
            name: "attendance_records_attendance_session_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :learner_id,
          references(:learners,
            column: :id,
            name: "attendance_records_learner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:attendance_records, [:attendance_session_id, :learner_id],
             name: "attendance_records_unique_session_learner_index"
           )

    create table(:academic_years, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:personal_classrooms) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "personal_classrooms_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:academic_years) do
      add :name, :text, null: false
      add :start_date, :date, null: false
      add :end_date, :date, null: false
      add :active, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :personal_workspace_id,
          references(:personal_workspaces,
            column: :id,
            name: "academic_years_personal_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:academic_years, [:personal_workspace_id, :name],
             name: "academic_years_unique_workspace_year_index"
           )
  end

  def down do
    drop constraint(:academic_years, "academic_years_personal_workspace_id_fkey")

    drop_if_exists unique_index(:academic_years, [:personal_workspace_id, :name],
                     name: "academic_years_unique_workspace_year_index"
                   )

    alter table(:academic_years) do
      remove :personal_workspace_id
      remove :updated_at
      remove :inserted_at
      remove :active
      remove :end_date
      remove :start_date
      remove :name
    end

    drop constraint(:personal_classrooms, "personal_classrooms_academic_year_id_fkey")

    alter table(:personal_classrooms) do
      modify :academic_year_id, :uuid
    end

    drop table(:academic_years)

    drop constraint(:attendance_records, "attendance_records_attendance_session_id_fkey")

    drop constraint(:attendance_records, "attendance_records_learner_id_fkey")

    drop_if_exists unique_index(:attendance_records, [:attendance_session_id, :learner_id],
                     name: "attendance_records_unique_session_learner_index"
                   )

    drop table(:attendance_records)

    drop constraint(:attendance_sessions, "attendance_sessions_personal_classroom_id_fkey")

    drop_if_exists unique_index(:attendance_sessions, [:personal_classroom_id, :date],
                     name: "attendance_sessions_unique_classroom_date_index"
                   )

    drop table(:attendance_sessions)

    drop constraint(:learners, "learners_personal_classroom_id_fkey")

    drop table(:learners)

    drop constraint(:lesson_plan_entries, "lesson_plan_entries_personal_classroom_id_fkey")

    alter table(:lesson_plan_entries) do
      remove :personal_classroom_id
      remove :updated_at
      remove :inserted_at
      remove :objectives
      remove :planned_hours
      remove :planned_on
      remove :title
    end

    drop constraint(:teaching_log_entries, "teaching_log_entries_lesson_plan_entry_id_fkey")

    alter table(:teaching_log_entries) do
      modify :lesson_plan_entry_id, :uuid
    end

    drop table(:lesson_plan_entries)

    drop constraint(:personal_classrooms, "personal_classrooms_personal_workspace_id_fkey")

    drop_if_exists unique_index(
                     :personal_classrooms,
                     [:personal_workspace_id, :academic_year_id, :class_label, :subject],
                     name: "personal_classrooms_unique_workspace_class_subject_year_index"
                   )

    drop table(:personal_classrooms)

    drop constraint(:personal_workspaces, "personal_workspaces_owner_user_id_fkey")

    drop_if_exists unique_index(:personal_workspaces, [:owner_user_id],
                     name: "personal_workspaces_unique_owner_user_index"
                   )

    drop table(:personal_workspaces)

    drop table(:teaching_log_entries)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
