defmodule TeacherAssistant.Repo.Migrations.AddFeeAdjustment do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:fee_adjustments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :amount, :bigint, null: false
      add :reason, :text, null: false
      add :recorded_by_user_id, :uuid
      add :workspace_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :enrollment_id,
          references(:enrollments,
            column: :id,
            name: "fee_adjustments_enrollment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:fee_adjustments, [:enrollment_id],
             name: "fee_adjustments_unique_adjustment_index"
           )
  end

  def down do
    drop constraint(:fee_adjustments, "fee_adjustments_enrollment_id_fkey")

    drop_if_exists unique_index(:fee_adjustments, [:enrollment_id],
                     name: "fee_adjustments_unique_adjustment_index"
                   )

    drop table(:fee_adjustments)
  end
end
