defmodule TeacherAssistant.Repo.Migrations.MigrateResources6 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:progression_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :module, :text, null: false
      add :lesson_title, :text, null: false
      add :planned_hours, :decimal, default: "1"
      add :entry_type, :text, default: "lesson"
      add :week_no, :bigint
      add :position, :bigint, null: false
      add :famille_de_situations, :text
      add :categories_action, :text
      add :competence_visee, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :progression_plan_id,
          references(:progression_plans,
            column: :id,
            name: "progression_entries_progression_plan_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :sequence_id,
          references(:sequences,
            column: :id,
            name: "progression_entries_sequence_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:progression_entries, "progression_entries_progression_plan_id_fkey")

    drop constraint(:progression_entries, "progression_entries_sequence_id_fkey")

    drop table(:progression_entries)
  end
end
