defmodule TeacherAssistant.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:school_profiles) do
      add :class_coefficients_allowed?, :boolean, null: false, default: true
      add :bulletin_group_subtotals?, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:school_profiles) do
      remove :bulletin_group_subtotals?
      remove :class_coefficients_allowed?
    end
  end
end
