defmodule TeacherAssistant.Repo.Migrations.AddClassGroups do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :email, :citext, null: false
      add :role, :text, default: "teacher"
      add :hashed_password, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:terms, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :position, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :academic_year_id, :uuid, null: false
    end

    create unique_index(:terms, [:academic_year_id, :position],
             name: "terms_unique_year_term_index"
           )

    create table(:teaching_log_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :date, :date, null: false
      add :content_taught, :text, null: false
      add :hours, :decimal, default: "1"
      add :status, :text, null: false, default: "done"
      add :homework, :text
      add :note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :personal_workspace_id, :uuid, null: false
      add :progression_entry_id, :uuid
    end

    create table(:teaching_contexts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :subject, :text, null: false
      add :level, :text, null: false
      add :serie, :text
      add :subsystem, :text, null: false
      add :weekly_hours, :bigint, default: 4

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :personal_workspace_id, :uuid, null: false
      add :academic_year_id, :uuid, null: false
    end

    create unique_index(
             :teaching_contexts,
             [:personal_workspace_id, :academic_year_id, :subject, :level, :serie],
             name: "teaching_contexts_unique_context_index"
           )

    create table(:sequences, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :number, :bigint, null: false
      add :position_in_term, :bigint, null: false
      add :start_date, :date, null: false
      add :end_date, :date, null: false
      add :integration_week, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :term_id,
          references(:terms,
            column: :id,
            name: "sequences_term_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create table(:progression_plans, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :title, :text, null: false
      add :status, :text, default: "draft"
      add :template, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :teaching_context_id,
          references(:teaching_contexts,
            column: :id,
            name: "progression_plans_teaching_context_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :academic_year_id, :uuid, null: false
      add :personal_workspace_id, :uuid, null: false
    end

    create table(:progression_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :module, :text, null: false
      add :lesson_title, :text, null: false
      add :planned_hours, :decimal, default: "1"
      add :entry_type, :text, null: false, default: "lesson"
      add :week_no, :bigint
      add :position, :bigint, null: false
      add :famille_de_situations, :text
      add :categories_action, :text
      add :competence_visee, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :progression_plan_id,
          references(:progression_plans,
            column: :id,
            name: "progression_entries_progression_plan_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :sequence_id,
          references(:sequences,
            column: :id,
            name: "progression_entries_sequence_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:personal_workspaces, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:teaching_log_entries) do
      modify :personal_workspace_id,
             references(:personal_workspaces,
               column: :id,
               name: "teaching_log_entries_personal_workspace_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :progression_entry_id,
             references(:progression_entries,
               column: :id,
               name: "teaching_log_entries_progression_entry_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:teaching_contexts) do
      modify :personal_workspace_id,
             references(:personal_workspaces,
               column: :id,
               name: "teaching_contexts_personal_workspace_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:personal_workspaces) do
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_user_id,
          references(:users,
            column: :id,
            name: "personal_workspaces_owner_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:personal_workspaces, [:owner_user_id],
             name: "personal_workspaces_unique_owner_user_index"
           )

    create table(:class_groups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :label, :text, null: false
      add :level, :text, null: false
      add :serie, :text
      add :subsystem, :text, null: false, default: "francophone"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :personal_workspace_id,
          references(:personal_workspaces,
            column: :id,
            name: "class_groups_personal_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :academic_year_id, :uuid, null: false
    end

    create unique_index(:class_groups, [:personal_workspace_id, :academic_year_id, :label],
             name: "class_groups_unique_class_group_index"
           )

    create table(:academic_years, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:terms) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "terms_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:teaching_contexts) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "teaching_contexts_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:progression_plans) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "progression_plans_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :personal_workspace_id,
             references(:personal_workspaces,
               column: :id,
               name: "progression_plans_personal_workspace_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:class_groups) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "class_groups_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:academic_years) do
      add :name, :text, null: false
      add :start_date, :date, null: false
      add :end_date, :date, null: false
      add :active, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :personal_workspace_id,
          references(:personal_workspaces,
            column: :id,
            name: "academic_years_personal_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:academic_years, [:personal_workspace_id, :name],
             name: "academic_years_unique_workspace_year_index"
           )
  end

  def down do
    drop constraint(:academic_years, "academic_years_personal_workspace_id_fkey")

    drop_if_exists unique_index(:academic_years, [:personal_workspace_id, :name],
                     name: "academic_years_unique_workspace_year_index"
                   )

    alter table(:academic_years) do
      remove :personal_workspace_id
      remove :updated_at
      remove :inserted_at
      remove :active
      remove :end_date
      remove :start_date
      remove :name
    end

    drop constraint(:class_groups, "class_groups_academic_year_id_fkey")

    alter table(:class_groups) do
      modify :academic_year_id, :uuid
    end

    drop constraint(:progression_plans, "progression_plans_academic_year_id_fkey")

    drop constraint(:progression_plans, "progression_plans_personal_workspace_id_fkey")

    alter table(:progression_plans) do
      modify :personal_workspace_id, :uuid
      modify :academic_year_id, :uuid
    end

    drop constraint(:teaching_contexts, "teaching_contexts_academic_year_id_fkey")

    alter table(:teaching_contexts) do
      modify :academic_year_id, :uuid
    end

    drop constraint(:terms, "terms_academic_year_id_fkey")

    alter table(:terms) do
      modify :academic_year_id, :uuid
    end

    drop table(:academic_years)

    drop constraint(:class_groups, "class_groups_personal_workspace_id_fkey")

    drop_if_exists unique_index(
                     :class_groups,
                     [:personal_workspace_id, :academic_year_id, :label],
                     name: "class_groups_unique_class_group_index"
                   )

    drop table(:class_groups)

    drop constraint(:personal_workspaces, "personal_workspaces_owner_user_id_fkey")

    drop_if_exists unique_index(:personal_workspaces, [:owner_user_id],
                     name: "personal_workspaces_unique_owner_user_index"
                   )

    alter table(:personal_workspaces) do
      remove :owner_user_id
      remove :updated_at
      remove :inserted_at
      remove :name
    end

    drop constraint(:teaching_contexts, "teaching_contexts_personal_workspace_id_fkey")

    alter table(:teaching_contexts) do
      modify :personal_workspace_id, :uuid
    end

    drop constraint(:teaching_log_entries, "teaching_log_entries_personal_workspace_id_fkey")

    drop constraint(:teaching_log_entries, "teaching_log_entries_progression_entry_id_fkey")

    alter table(:teaching_log_entries) do
      modify :progression_entry_id, :uuid
      modify :personal_workspace_id, :uuid
    end

    drop table(:personal_workspaces)

    drop constraint(:progression_entries, "progression_entries_progression_plan_id_fkey")

    drop constraint(:progression_entries, "progression_entries_sequence_id_fkey")

    drop table(:progression_entries)

    drop constraint(:progression_plans, "progression_plans_teaching_context_id_fkey")

    drop table(:progression_plans)

    drop constraint(:sequences, "sequences_term_id_fkey")

    drop table(:sequences)

    drop_if_exists unique_index(
                     :teaching_contexts,
                     [:personal_workspace_id, :academic_year_id, :subject, :level, :serie],
                     name: "teaching_contexts_unique_context_index"
                   )

    drop table(:teaching_contexts)

    drop table(:teaching_log_entries)

    drop_if_exists unique_index(:terms, [:academic_year_id, :position],
                     name: "terms_unique_year_term_index"
                   )

    drop table(:terms)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
