defmodule TeacherAssistant.Repo.Migrations.AssessmentTenancy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:assessments, [:teaching_context_id])

    create index(:assessments, [:workspace_id, :teaching_context_id])

    drop_if_exists index(:assessments, [:sequence_id])

    create index(:assessments, [:workspace_id, :sequence_id])

    drop_if_exists index(:assessments, [:workspace_id])

    create index(:assessments, [:workspace_id])

    drop_if_exists unique_index(:marks, [:assessment_id, :student_id],
                     name: "marks_unique_mark_index"
                   )

    drop constraint(:marks, "marks_assessment_id_fkey")

    create unique_index(:marks, [:workspace_id, :assessment_id, :student_id],
             name: "marks_unique_mark_index"
           )

    alter table(:marks) do
      modify :assessment_id,
             references(:assessments,
               column: :id,
               name: "marks_assessment_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:marks, [:assessment_id])

    create index(:marks, [:workspace_id, :assessment_id])

    drop_if_exists index(:marks, [:student_id])

    create index(:marks, [:workspace_id, :student_id])

    drop_if_exists index(:marks, [:workspace_id])

    create index(:marks, [:workspace_id])
  end

  def down do
    drop_if_exists index(:marks, [:workspace_id])

    create index(:marks, [:workspace_id])

    drop_if_exists index(:marks, [:workspace_id, :student_id])

    create index(:marks, [:student_id])

    drop_if_exists index(:marks, [:workspace_id, :assessment_id])

    create index(:marks, [:assessment_id])

    drop constraint(:marks, "marks_assessment_id_fkey")

    alter table(:marks) do
      modify :assessment_id,
             references(:assessments,
               column: :id,
               name: "marks_assessment_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists unique_index(:marks, [:workspace_id, :assessment_id, :student_id],
                     name: "marks_unique_mark_index"
                   )

    create unique_index(:marks, [:assessment_id, :student_id], name: "marks_unique_mark_index")

    drop_if_exists index(:assessments, [:workspace_id])

    create index(:assessments, [:workspace_id])

    drop_if_exists index(:assessments, [:workspace_id, :sequence_id])

    create index(:assessments, [:sequence_id])

    drop_if_exists index(:assessments, [:workspace_id, :teaching_context_id])

    create index(:assessments, [:teaching_context_id])
  end
end
