defmodule TeacherAssistant.Repo.Migrations.FeeAdjustmentPositive do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(:fee_adjustments, :fee_adjustments_amount_non_zero_check)

    create constraint(:fee_adjustments, :fee_adjustments_amount_positive_check,
             check: """
               amount > 0
             """
           )
  end

  def down do
    drop_if_exists constraint(:fee_adjustments, :fee_adjustments_amount_positive_check)

    create constraint(:fee_adjustments, :fee_adjustments_amount_non_zero_check,
             check: """
               amount <> 0
             """
           )
  end
end
